### ISSUE TITLE
Support for SPARC cpu's?

### ISSUE THREAD

**Issue by sbktx** [Dr-Noob/cpufetch#100]
Just curious if you'd consider adding support for sparc cpu's, i know that there's not a big user-base of sparc based machines anymore though there still are some of us out there! A possible logo could be this, which is from the wikipedia page for the sparc processors-
https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Sparc-logo.svg/1200px-Sparc-logo.svg.png

There's a few modern os's which still support sparc64- debian sid, gentoo, netbsd, openbsd, and freebsd being the ones i'm aware of. As of freebsd 13 however the sparc64 build was dropped, but there is a version for freebsd 12, and the other 2 bsd's have pretty good support for sparc64.

I have a sun fire v245 with an ultrasparc IIIi running debian and netbsd you can use for testing if you'd like.

That's if you want to, I get this is a pretty niche platform these days

**Comment by Dr-Noob** [comment]
Hi, thanks for your suggestion.

Unfortunately, I'm not considering adding CPU architectures with very few users these days. I understand that for people that own rare processors like yours would be great, but my goal with cpufetch is not to support everything out there (which may seem my goal after the port to PowerPC). Adding a new CPU architecture needs a lot of work and also adds a lot of complexity to the source code.

If you really wish this to happen, your best bet is to fork the project and try to make it yourself. In the [cpufetch documentation](https://github.com/Dr-Noob/cpufetch/blob/master/doc/README.md) you can find a decent explanation for each CPU backend. Maybe you can get some ideas of how to support another CPU by looking at those explanations. But I won't make it happen, sorry :(

Closing
