### ISSUE TITLE
Expanding the installation instructions

### ISSUE THREAD

**Issue by kmanwar89** [Dr-Noob/cpufetch#102]
Hello,

I'm on a fresh install of Kubuntu 21.04. By default, it doesn't seem like it comes with the proper tools, so I thought it might be worthwhile to mention in the readme that _make_ and _gcc_ are needed to compile from source.

I was receiving an error 127 (as witnessed in the output below) until I installed GCC. Hopefully this helps someone else as well.

```
gcc -Wall -Wextra -Werror -pedantic -fstack-protector-all -pedantic -std=c99 -DARCH_X86 -Wfloat-equal -Wshadow -Wpointer-arith src/common/main.c src/common/cpu.c src/common/udev.c src/common/printer.c src/common/args.c src/common/global.c src/x86/cpuid.c src/x86/apic.c src/x86/cpuid_asm.c src/x86/uarch.c -o cpufetch
make: gcc: No such file or directory
make: *** [Makefile:45: cpufetch] Error 127

```

**Comment by Dr-Noob** [comment]
Someone trying to compile a C program should expect that a C compiler is needed to do so. Anyway, it is not a bad idea to say that explicitly in the Makefile, so I've slightly rephrased the Makefile to do so. Thanks for the suggestion.

Closing.
