### ISSUE TITLE
CPU name change

### ISSUE THREAD

**Issue by Trqhxrd** [Dr-Noob/cpufetch#103]
Is it possible to make it say "Hexa-Core" or "Octa-Core" instead of "Six-Core"? It would probanly sound cooler.

**Comment by Dr-Noob** [comment]
Thanks for the suggestion, but I don't like the idea. Showing the number is more accurate. Don't you think that the output for a CPU like https://github.com/Dr-Noob/cpufetch/blob/master/pictures/epyc.png would look a bit odd?

Closing.
