### ISSUE TITLE
Tested cpufetch on Android x86

### ISSUE THREAD

**Issue by abdullah-if** [Dr-Noob/cpufetch#107]
Just tested cpufetch on Android x86. Ran without any hassel. Any special test case required?\
On Termux
![Screen_Capture_Img_5306](https://user-images.githubusercontent.com/54185653/129912746-c1296aeb-bfe4-4866-b904-dcf066ca885d.png)

**Comment by Dr-Noob** [comment]
That's nice!  It was in my TODO list this week, but you did it first. We can conclude that it works under Android x86. There is no additional test case to try. I'll update the README soon to update the table. Thanks!
