### ISSUE TITLE
Add cpufetch to brew package manager (macOS)

### ISSUE THREAD

**Issue by Dr-Noob** [Dr-Noob/cpufetch#108]
Does anybody know how to do so and is willing to help? It should work for ARM (Apple M1) and also x86 macOS

**Comment by lmartinez-mirror** [comment]
I have a prototype Brew script, but I haven't submitted it to Homebrew upstream yet. I need to make sure it passes their guidelines.

**Comment by Dr-Noob** [comment]
That's nice! Let me know if you need any further changes to the Makefile or something.

**Comment by lmartinez-mirror** [comment]
[Now to play the waiting game.](https://github.com/Homebrew/homebrew-core/pull/84631)

**Comment by lmartinez-mirror** [comment]
[It is done.](https://github.com/Homebrew/homebrew-core/commit/29d316fb938ebf1569b024fe5fe1ac5a8a648ec4)

**Comment by Dr-Noob** [comment]
That's nice, thanks a lot! I have just tried it and works perfectly. I have one question, will it work in ARM macOS too?

I'll add you to the list of fellow contributors of the project in the README. Thanks for your time!
