### ISSUE TITLE
AMD Raven Ridge (Dali)

### ISSUE THREAD

**Issue by unixfg** [Dr-Noob/cpufetch#115]
cpufetch v1.00 (Linux x86_64 build)
AMD Athlon Silver 3050e with Radeon Graphics
- Max standard level: 0x0000000D
- Max extended level: 0x8000001F
- AMD topology extensions: 1
- CPUID dump: 0x00820F01

**Comment by Dr-Noob** [comment]
Thanks for the warning, I have just fixed the issue. Give it a try again and let me know if there is any problem. Closing
