### ISSUE TITLE
manpage  useless-whatis-entry

### ISSUE THREAD

**Issue by ClayStan** [Dr-Noob/cpufetch#118]
Hey, Dr-Noob
I notice that you generate the manpage by help2man tool,
about the line 4 https://github.com/Dr-Noob/cpufetch/blob/3641391bd8c251aab73212f6769ec5dc4887fa02/cpufetch.1#L4

The whatis entry for this manual page (the brief description found in the NAME section) is of the form:

program - manual page for program

This conveys no information about what the program is for and is repetitive. The short description should contain brief information about what the program is for to aid in searching with apropos and similar programs.

If this manual page was generated by help2man, use the -n option to provide a more meaningful description.

I think you can replace "manual page for cpufetch v0.99 (Linux x86_64 build)" with "Simple yet fancy CPU architecture fetching tool", as before

reference : https://lintian.debian.org/tags/useless-whatis-entry

**Comment by Dr-Noob** [comment]
Thanks a lot, @ClayStan. You are absolutely right. I noticed the issue, but I didn't know a clean way to replace the redundant description (didn't know about `-n`). I have updated the manual page to change it. Closing.
