### ISSUE TITLE
Add cpufetch to termux package manager (Android)

### ISSUE THREAD

**Issue by Dr-Noob** [Dr-Noob/cpufetch#123]
https://github.com/termux/termux-packages

**Comment by AnGelXoG** [comment]
Little will be added I think since I already saw that they are doing it XD

**Comment by Dr-Noob** [comment]
I just saw your issue in the termux repository. Thanks a lot @AnGelXoG, and thanks to @ELWAER-M for including it! That's awesome!

Closing.
