### ISSUE TITLE
my cpu is unknow？

### ISSUE THREAD

**Issue by shepf** [Dr-Noob/cpufetch#125]
![1635305694(1)](https://user-images.githubusercontent.com/25335472/138995761-a1584b24-13f6-4207-8bbb-4a35efa36f3b.png)

# lscpu
Architecture:        aarch64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per socket:  4
Socket(s):           1
Vendor ID:           0x70
Model:               3
Model name:          FT-2000/4
Stepping:            0x1
CPU max MHz:         2600.0000
CPU min MHz:         1900.0000
BogoMIPS:            96.00
Flags:               half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32

**Comment by Dr-Noob** [comment]
Wow, that's a quite interesting CPU. Looks like a Phytium FT-2000/4 (https://en.wikipedia.org/wiki/FeiTeng_(processor):
- Microarchitecture: Xiaomi
- SoC: Mars I
- Technology: 16 nm

Am I right?

I have updated the `bugfix` branch. Please try it again in this branch, the microarchitecture detection should work now. I also need the output of `cpufetch --verbose` to keep working on this. Thanks!

**Comment by Dr-Noob** [comment]
The patch has been merged into master, I'm closing the issue. Reopen it if you need further asistance.
