### ISSUE TITLE
[Makefile:76: cpufetch] Error 1

### ISSUE THREAD

**Issue by msr8** [Dr-Noob/cpufetch#127]
I am using termux on Redmi Note 6 Pro with the OS Android 9, I have successfully ran `pkg install -y git make clang` inside the terminal and cloned this repo, however when I am cd-ing into the folder and running the `make` command, the following error is coming:

```
$ cd cpufetch/
$ make
cc -Wall -Wextra -pedantic -DARCH_ARM -Wno-unused-parameter -std=c99 -fstack-protector-all -O2 -Wfloat-equal -Wshadow -Wpointer-arith src/common/main.c src/common/cpu.c src/common/udev.c src/common/printer.c src/common/args.c src/common/global.c src/arm/midr.c src/arm/uarch.c src/arm/soc.c src/arm/udev.c -o cpufetch
CANNOT LINK EXECUTABLE "cc": cannot locate symbol "__emutls_get_address" referenced by "/data/data/com.termux/files/usr/lib/libclang-cpp.so"...
make: * [Makefile:76: cpufetch] Error 1
```

**Comment by Dr-Noob** [comment]
Not related to cpufetch, looks like something broke recently in termux. See [this reddit post](https://www.reddit.com/r/termux/comments/qljecl/cant_compile_c_cannot_link_executable/). Maybe updating the packages fixes the issue?

**Comment by msr8** [comment]
Turns out I was using the depreciated version of Termux which I had downloaded from the playstore. I downloaded the latest version by following the instruction in Termux's github page and now cpufetch works. Thank you!
