### ISSUE TITLE
RISC-V support

### ISSUE THREAD

**Issue by Popolon** [Dr-Noob/cpufetch#133]
When I try to compile on RISC-V (64 bit version) of Debian.
<pre>
root@debian:~/cpufetch# make
Makefile:45: Unsupported arch detected: riscv64. See https://github.com/Dr-Noob/cpufetch#1-support
Makefile:46: If your architecture is supported but the compilation fails, please open an issue in https://github.com/Dr-Noob/cpufetch/issues
Makefile:47: *** Aborting compilation. Arrêt.
</pre>

For information on my qemu installation of Debian, I have the following /proc/cpuinfo
<pre>
processor       : 0
hart            : 1
isa             : rv64imafdcsu
mmu             : sv48
</pre>
rv32 means RISC-V 32 bits rv64, 64 bits and rv128 128 bits (still in draft). the letter that follow are the names of the extensions:
* i=integer
* m=mutiply(and divde)
* f=float, d=double
etc...
I have some RISC-V 32 bits and 64 bits MCU, but without MMU. I wait for a RISC-V purpose CPU to test Linux on real hardware RISC-V. Several cheap boards should be available this month.

**Comment by Dr-Noob** [comment]
Yes, this is expected. 

Currently, cpufetch does not run on RISC-V, and I do not have the intention to add support to it shortly (see #101). Maybe next summer, maybe next year... If I can get access to real hardware I will probably change my mind and add support much sooner, so if you can offer anything, I will listen :thinking:.

Closing.

**Comment by Popolon** [comment]
OK, as it was closed I didn't found anything when searching for RISC-V, sorry.

**Comment by yuzibo** [comment]
Hi, @Dr-Noob I have the riscv64 machine by hand, please how to help here?

**Comment by Popolon** [comment]
Sorry, I'm already busy on porting packages and systems since few month on RISC-V, which board do you use. I use mainly Sipeed Lichee-RV for these ports.

**Comment by yuzibo** [comment]
Thank your work:) Once done, I will forward this to maintainer of cpufetch Debian packages.
Background: I am fixing some debian packages on  riscv64 that have ftbfs: https://buildd.debian.org/status/package.php?p=cpufetch&suite=sid.
