### ISSUE TITLE
Unable to detect Google Tensor

### ISSUE THREAD

**Issue by rowheel** [Dr-Noob/cpufetch#134]
![Screenshot_20211217-181338.png](https://user-images.githubusercontent.com/29014642/146528550-16c5b21e-b29d-42b7-9863-cfaba2a72b69.png)

The device is a Pixel 6

**Comment by Dr-Noob** [comment]
Hey, thanks for the report.

Seems like you installed the program using `termux`. It's fine, but it does not contain the latest `cpufetch` version. Anyway, if you wanna test the latest patch I just submited, you need to compile it by yourself. It's very easy, see [install cpufetch on Android](https://github.com/Dr-Noob/cpufetch#23-android).

I've updated the program in the `feat2` branch. It should work perfectly now. Could you download the code and see how it goes? Remember to do `git checkout feat2` before compiling.

**Comment by das-rob3rt** [comment]
![Screenshot_20211218-231133.png](https://user-images.githubusercontent.com/29014642/146645934-2d65118b-c816-48c6-8476-09ab71e5f167.png)

Hmmm... But the technology field is still "unknown" 😂

**Comment by Dr-Noob** [comment]
Ok, that was strange. Please, try the latest commit in `feat2` (you can just do `git pull` and compile again).

**Comment by Dr-Noob** [comment]
Please run `./cpufetch -v` (using the latest commit) and paste the output here.

**Comment by das-rob3rt** [comment]
> Please run `./cpufetch -v` (using the latest commit) and paste the output here.

OK, and off you go -

![Screenshot_20211220-101552.png](https://user-images.githubusercontent.com/29014642/146702365-00496aba-6c3f-4e1c-b38d-e19f2443af8e.png)

**Comment by das-rob3rt** [comment]
> Please run `./cpufetch -v` (using the latest commit) and paste the output here.

And btw - just allow me to ask about a private question: how do you debug this program? Is that through `gdbserver`? 😃

**Comment by Dr-Noob** [comment]
> > Please run `./cpufetch -v` (using the latest commit) and paste the output here.
> 
> OK, and off you go -
> 
> ![Screenshot_20211220-101552.png](https://user-images.githubusercontent.com/29014642/146702365-00496aba-6c3f-4e1c-b38d-e19f2443af8e.png)

Are you sure you are using the latest commit? The commit hash is `1fab1ee`. If you are, I'm out of ideas, the SoC should be detected with the latest patch.

**Comment by Dr-Noob** [comment]
This should work with the latest patches in `master` branch. Closing the issue
