### ISSUE TITLE
License change

### ISSUE THREAD

**Issue by Tectu** [Dr-Noob/cpufetch#135]
Commit a4e1a837a31a3c59649222dc1f113ee6d89b28c3 changed the licensing model.
I'd like to ask whether you could provide some explanation/rationale that lead you to this decision?

Just to be extra clear here: I don't mean to complain about anything nor do I want to express preferences for one particular licensing scheme or license. I'd merely like to understand the reasoning behind this choice.

**Comment by Dr-Noob** [comment]
My main concern with the MIT license was that if a proprietary project uses the code from cpufetch (total or partially), it is not necessary to make the code open source. In the end, this means that if someone is using my project for anything (especially for lucrative purposes), I would never be aware of such a situation. With GPL, this is not allowed.

**Comment by Tectu** [comment]
Thank you for providing your reasoning behind this :)

Looking forward to the next release!
