### ISSUE TITLE
CPU Unknown 12gen Intel

### ISSUE THREAD

**Issue by rzwarts74** [Dr-Noob/cpufetch#136]
cpufetch --debug

`[ERROR]: Unknown microarchitecture detected: M=0x00000007 EM=0x00000009 F=0x00000006 EF=0x00000000 S=0x00000002
Please, create a new issue with this error message, the output of 'cpufetch' and 'cpufetch --debug' on https://github.com/Dr-Noob/cpufetch/issues
cpufetch v1.01 (Linux x86_64 build)
12th Gen Intel(R) Core(TM) i7-12700K
- Max standard level: 0x00000020
- Max extended level: 0x80000008
- CPUID dump: 0x00090672
`
![Screenshot from 2022-01-24 18-28-44](https://user-images.githubusercontent.com/38145677/150834331-ec76626d-3985-4a51-bbe7-a2a2317ea088.png)

**Comment by rzwarts74** [comment]
https://ark.intel.com/content/www/us/en/ark/products/134594/intel-core-i712700k-processor-25m-cache-up-to-5-00-ghz.html

**Comment by Dr-Noob** [comment]
I have pushed a new commit to `bugfix2` branch. 

It should detect the uarch, but still unable to properly detect the number of cores. I will work on the latter whenever I have direct access to an Alder Lake CPU.

**Comment by philipl** [comment]
Happy to report the branch worked correctly for me.

**Comment by rzwarts74** [comment]
I have an AL CPU... What do you need @Dr-Noob ?

**Comment by rzwarts74** [comment]
And how do I check the bugfix2 ? #

> I have pushed a new commit to `bugfix2` branch.
> 
> It should detect the uarch, but still unable to properly detect the number of cores. I will work on the latter whenever I have direct access to an Alder Lake CPU.

How do I access this on my machine ? @Dr-Noob

**Comment by rzwarts74** [comment]
You can see the number of P & E cores here https://ark.intel.com/content/www/us/en/ark/products/series/217837/12th-generation-intel-core-i7-processors.html

**Comment by Dr-Noob** [comment]
> And how do I check the bugfix2 ? #
> 
> > I have pushed a new commit to `bugfix2` branch.
> > It should detect the uarch, but still unable to properly detect the number of cores. I will work on the latter whenever I have direct access to an Alder Lake CPU.
> 
> How do I access this on my machine ? @Dr-Noob

You can check bugfix2 by issuing: `git checkout bugfix2`

**Comment by Dr-Noob** [comment]
I merged this into master branch so I'm closing this issue. Feel free to reopen it or open a new one if you find further issues.
