### ISSUE TITLE
Warning during build in src/x86/cpuid.c

### ISSUE THREAD

**Issue by bbonev** [Dr-Noob/cpufetch#138]
gcc 11.2.0
CFLAGS=-Wall -Wextra -pedantic -pthread -DARCH_X86 -std=c99 -fstack-protector-all -O2 -Wfloat-equal -Wshadow -Wpointer-arith

```` c
src/x86/cpuid.c: In function ‘get_topology_from_udev’:
src/x86/cpuid.c:475:45: warning: unused parameter ‘cpu’ [-Wunused-parameter]
  475 | void get_topology_from_udev(struct cpuInfo* cpu, struct topology* topo) {
      |                             ~~~~~~~~~~~~~~~~^~~
````

**Comment by Dr-Noob** [comment]
You are not compiling the clean, master branch. [Are you?](https://github.com/Dr-Noob/cpufetch/blob/4229e2c63b43884bd08c0609717d4d40c01d3013/src/x86/cpuid.c#L483)

**Comment by bbonev** [comment]
No, this is tag v1.01, forgot to mention that...

**Comment by bbonev** [comment]
Just verified that this problem is not there on master...
