### ISSUE TITLE
v1.01 release

### ISSUE THREAD

**Issue by Tectu** [Dr-Noob/cpufetch#140]
Hi!

I'd like to inquire information regarding the schedule of the v1.01 release? Is there any roadmap for this?
I'd really like to update the FreeBSD port but we don't usually update the port without a proper upstream release.

**Comment by Dr-Noob** [comment]
Hey,

I was not aware of people expecting releases, but sure. I'll take that into account for future versions. I was thinking about jumping to the next version, so I took the opportunity and applied some old patches to v1.01 and jumped to v1.02, for which I just created a release (btw, with a FreeBSD statically linked binary, which was not present in the previous release).

Closing.

**Comment by Tectu** [comment]
`v1.02` is now available from FreeBSD ports: https://cgit.freebsd.org/ports/commit/?id=a251897b451239f25f9cf6bcd6c0fa16ff6bd916
