### ISSUE TITLE
Add output to png/jpg image

### ISSUE THREAD

**Issue by trevor-vincent** [Dr-Noob/cpufetch#146]
Thank you for your awesome project Dr-Noob! It would be nice to have a png or jpg image we can share with people.

**Comment by Dr-Noob** [comment]
That's something I also thought about in the past, but I don't see any clean way to integrate that in a C/C++ project. There seem to be ways of [doing that with external programs](https://unix.stackexchange.com/questions/138804/how-to-transform-a-text-file-into-a-picture) but looks too heavy to integrate into this project, so I don't think I'll be adding that.
