### ISSUE TITLE
[ERROR]: Shared map length is 18 while the max is be 9

### ISSUE THREAD

**Issue by pkubaj** [Dr-Noob/cpufetch#152]
This is on Gentoo with Linux 5.19.0. Additionally, cache sizes are wrong.
Here's a screenshot: https://imgur.com/buCa8tD.png

Here are cache sizes lscpu reports:
```
Caches (sum of all):   
  L1d:                 512 KiB (16 instances)
  L1i:                 512 KiB (16 instances)
  L2:                  8 MiB (16 instances)
  L3:                  160 MiB (16 instances)
```

**Comment by Dr-Noob** [comment]
That was such a big stupid check I introduced a while ago. I just removed it, but I still think it won't work on your machine. Can you try again? Also, if you find any issues, please paste the output of `cat /sys/devices/system/cpu/cpu0/cache/index0/shared_cpu_map`

**Comment by pkubaj** [comment]
It now looks ok and the cache size is also ok, thanks:
![Przechwycenie obrazu ekranu_2022-09-06_15-42-03](https://user-images.githubusercontent.com/4457924/188650554-099a8d86-5cd3-4b5a-9790-ca5c816c518c.png)

**Comment by pkubaj** [comment]
Oh, wait, the cache size is correct for a single CPU, but this is dual CPU system, so it should actually be doubled.

**Comment by Dr-Noob** [comment]
Probably a bug when parsing `/sys/devices/system/cpu/cpu*/cache/index0/shared_cpu_map`. Would you paste the output of `cat /sys/devices/system/cpu/cpu0/cache/index0/shared_cpu_map`?

**Comment by pkubaj** [comment]
`00000000,0000000f`

**Comment by Dr-Noob** [comment]
I have pushed a fix in the bugfix branch. Can you try it and see if it works?

**Comment by pkubaj** [comment]
Indeed, thank you!
