### ISSUE TITLE
my cpu is unknow？

### ISSUE THREAD

**Issue by exkc** [Dr-Noob/cpufetch#165]
![Screenshot_2022-12-10_05-01-19](https://user-images.githubusercontent.com/70055899/209175400-0252120b-1df3-4e6c-b0cc-55e567e93efd.png)

# lscpu

![Screenshot_2022-12-10_05-04-51](https://user-images.githubusercontent.com/70055899/209175547-662339e0-ab99-463c-a93e-97aea5c54ba2.png)

# Device Info

Brand : Xiaomi
Vendor : Wingtech
Name : Redmi 2
Model : wt88047 (2014817)
Soc : Qualcomm Snapdragon 410
Ram : 1GB
Swap : 7.06GB
OS : postmarkert os
Degoogled : yes
Deandroided : yes
Bootloader : my fork of lk1st

**Comment by exkc** [comment]
i think it is a os issue . not sure do we have any workaround for it.

**Comment by Dr-Noob** [comment]
Run cpufetch in verbose mode (e.g., `./cpufetch -v`) to gather extra information and paste it here to see if we can do something about it.

**Comment by exkc** [comment]
![Screenshot_20221223-030154_Termux](https://user-images.githubusercontent.com/70055899/209207955-4e5399bc-4646-4a4f-ab24-0b12124e9705.png)

**Comment by Dr-Noob** [comment]
Yup, that means that there is no way to identify your SoC. 

I also have postmarketOS in my phone and it happens the same - Linux does not show the necessary field in `/proc/cpuinfo`. There is nothing cpufetch can do to solve it, closing.

**Comment by exkc** [comment]
Ok i guess u should pin this issue bc it is a common issue
