### ISSUE TITLE
[ERROR]: Unknown microarchitecture detected: M=0x0000000A EM=0x00000009 F=0x00000006 EF=0x00000000 S=0x00000003

### ISSUE THREAD

**Issue by omniplex** [Dr-Noob/cpufetch#166]
cpufetch v1.00 (Windows x86_64 build)
12th Gen Intel(R) Core(TM) i5-12450H
- Hypervisor: Microsoft Hyper-V
- Max standard level: 0x00000020
- Max extended level: 0x80000008
- CPUID dump: 0x000906A3

**Comment by Dr-Noob** [comment]
cpufetch has support for your CPU in the last release, but not in v1.00.

You will have to download the project and compile it yourself as explained [here](https://github.com/Dr-Noob/cpufetch#22-building-from-source) (also works for Windows). If you prefer to download a binary, you have it [here](https://github.com/Dr-Noob/cpufetch/releases/tag/v1.03), although I just checked that the v1.03 release will show partially incorrect information, but at least it will work.
