### ISSUE TITLE
Snapdragon 8+ Gen1 not displaying

### ISSUE THREAD

**Issue by Franscobec** [Dr-Noob/cpufetch#170]
![Screenshot_20230113_054013_Termux](https://user-images.githubusercontent.com/87747518/212301051-ffbe4675-67a4-4cec-9f84-46f93e7f52fb.jpg)
As shown in the screenshot cpufetch won't recognize the Snapdragon 8+ Gen1 in my device.

--Verbose:
[WARNING]: SoC detection failed using /proc/cpuinfo: No string found
[WARNING]: SoC detection failed using Android property ro.product.board: taro
[WARNING]: SoC detection failed using Android property ro.board.platform: taro
[WARNING]: SoC detection failed using Android: Found 'taro' string

--Debug:
[ERROR]: Unknown microarchitecture detected: IM=0x00000041 P=0x00000D46 V=0x00000000 R=0x00000003
Please, create a new issue with this error message, your smartphone/computer model, the output of 'cpufetch --verbose' and 'cpufetch --debug' on https://github.com/Dr-Noob/cpufetch/issues
[ERROR]: Unknown microarchitecture detected: IM=0x00000041 P=0x00000D47 V=0x00000002 R=0x00000000
Please, create a new issue with this error message, your smartphone/computer model, the output of 'cpufetch --verbose' and 'cpufetch --debug' on https://github.com/Dr-Noob/cpufetch/issues
[ERROR]: Unknown microarchitecture detected: IM=0x00000041 P=0x00000D48 V=0x00000002 R=0x00000000
Please, create a new issue with this error message, your smartphone/computer model, the output of 'cpufetch --verbose' and 'cpufetch --debug' on https://github.com/Dr-Noob/cpufetch/issues
cpufetch v1.02 (Android ARM build)
[Core 0] 0x410FD463 2016 MHz
[Core 1] 0x410FD463 2016 MHz
[Core 2] 0x410FD463 2016 MHz
[Core 3] 0x410FD463 2016 MHz
[Core 4] 0x412FD470 2745 MHz
[Core 5] 0x412FD470 2745 MHz
[Core 6] 0x412FD470 2745 MHz
[Core 7] 0x412FD480 3187 MHz

Device: Samsung Galaxy Z Fold4 (SM-F936W)

**Comment by Dr-Noob** [comment]
Seems like a duplicate of issue #158. Can you please test the fix in bugfix branch? Run in your termux:
```
pkg install -y git make clang
git clone https://github.com/Dr-Noob/cpufetch
cd cpufetch
git checkout bugfix
make
./cpufetch
```

**Comment by Franscobec** [comment]
The error still happens after doing that:
![Screenshot_20230113_161941_Termux](https://user-images.githubusercontent.com/87747518/212421273-bc7b02d1-bb77-47c2-a6a0-7dd6f2c8e282.jpg)

**Comment by Franscobec** [comment]
Nevermind, I didn't look properly that it didn't reinstall cpufetch properly

**Comment by Franscobec** [comment]
Redid it again after removing old cpufetch folder and it does it again

**Comment by Dr-Noob** [comment]
In your screenshot, you compile the program and then run `cpufetch`, which is running the installed program rather than the compiled one. Run `./cpufetch` (note the `./`) to execute the one you compiled and check if it works with that one.

**Comment by Franscobec** [comment]
Doing ./cpufetch gives me this:
bash: ./cpufetch: is a directory

**Comment by Dr-Noob** [comment]
You need to cd to the cpufetch directory first (e.g., `cd cpufetch && ./cpufetch`).

**Comment by Franscobec** [comment]
Gives me "segmentation fault"

**Comment by Dr-Noob** [comment]
Good! Thanks for the report - I have pushed a commit that fixes the segmentation fault. 

To try, run `cd cpufetch && git pull && make clean && make && ./cpufetch`.

**Comment by Franscobec** [comment]
![Screenshot_20230117_121231_Termux](https://user-images.githubusercontent.com/87747518/212966213-a2e130fe-0a02-4fff-bccb-9a3239edc3f0.jpg)

It works now. Only detail is that it shows up as 8 gen 1 (it is a 8+ gen1).
Thanks alot

**Comment by Dr-Noob** [comment]
Thank you for your feedback! I'll merge the changes in the master branch and see what I can do to show 8+ gen1 when appropriate.

**Comment by Dr-Noob** [comment]
So I have pushed a new commit that should now print 8+ in your phone. To check it, same as before: `cd cpufetch && git pull && make clean && make && ./cpufetch`

**Comment by Franscobec** [comment]
Alright, thanks
