### ISSUE TITLE
My cpu  microarchitecture not found in my AMD Ryzen 9 6900HS with Radeon Graphics

### ISSUE THREAD

**Issue by Quark04** [Dr-Noob/cpufetch#171]
```
[ERROR]: Unknown microarchitecture detected: M=0x00000004 EM=0x00000004 F=0x0000000F EF=0x0000000A S=0x00000001
Please, create a new issue with this error message, the output of 'cpufetch' and 'cpufetch --debug' on https://github.com/Dr-Noob/cpufetch/issues
[ERROR]: Found invalid process: '0'
Please, create a new issue with this error message, the output of 'cpufetch' and 'cpufetch --debug' on https://github.com/Dr-Noob/cpufetch/issues
```

On a Zephyrus ROG G14 (2022) laptop

**Comment by Quark04** [comment]
> Can you guys confirm you are running the last cpufetch version? You can check it with `cpufetch -V` and the lastest version is v1.03. If not, you can just try the [last release](https://github.com/Dr-Noob/cpufetch/releases/tag/v1.03) which includes binaries for windows.

I run a rolling release  distro and keep it very up to date so I'm pretty sure but I will confirm it to you in a second

**Comment by Quark04** [comment]
> Can you guys confirm you are running the last cpufetch version? You can check it with `cpufetch -V` and the lastest version is v1.03. If not, you can just try the [last release](https://github.com/Dr-Noob/cpufetch/releases/tag/v1.03) which includes binaries for windows.

Went to check and the AUR package for cpufetch is on 1.02 so I installed the git package and it works all good now

**Comment by Dr-Noob** [comment]
Good, so it was a matter of updating the package. Closing.
