### ISSUE TITLE
`invalid cpu_family: 0x00000000` on macOS Monterey arm build for cpufetch 1.0.4

### ISSUE THREAD

**Issue by chenrui333** [Dr-Noob/cpufetch#180]
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>error build log</summary>

```
  ==> /opt/homebrew/Cellar/cpufetch/1.04/bin/cpufetch -d
  [ERROR]: Found invalid cpu_family: 0x00000000
  [VERSION]: cpufetch v1.04 (macOS ARM build)
```

</details>

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/4904192481/jobs/8757081355?pr=130340
relates to Homebrew/homebrew-core#130340

**Comment by carlocab** [comment]
Note: this error is actually due to our use of virtualised ARM machines at Homebrew, and not an issue with `cpufetch`.

**Comment by Dr-Noob** [comment]
Exactly. If the hypervisor hides the value of `cpu_family`, there is nothing `cpufetch` can do about it. Closing.
