### ISSUE TITLE
Unknown microarchitecture when running on Intel 13th Gen Core i7-1355U

### ISSUE THREAD

**Issue by IsaacMilarky** [Dr-Noob/cpufetch#181]
Ran into an "Unknown microarchitecture detected" exception when running cpufetch on arch linux. Laptop is a Lenovo Yoga 7i. Program did not crash however. The exact cpu model number is 186 which is an Intel 13th Gen Core i7-1355U. From what it looks like this cpu has the 'Alderlake' microarchitecture but I could be wrong about that.

Output of `cpufetch`:
 
![image](https://github.com/Dr-Noob/cpufetch/assets/24639268/a3cec438-f29c-46bb-a6b3-b7006f11989f)

Output of `cpufetch --debug`:

![image](https://github.com/Dr-Noob/cpufetch/assets/24639268/f8d6ca1d-08d4-4e97-a166-48144b4b467d)

Output of `sudo cpufetch -v`

![image](https://github.com/Dr-Noob/cpufetch/assets/24639268/0af4ea72-f693-4c4c-8ef6-932e3e7f33fd)

**Comment by Dr-Noob** [comment]
Should be fixed in commit 6349f44. Can you confirm?

**Comment by IsaacMilarky** [comment]
Yes it is fixed now! :)
