### ISSUE TITLE
Apple M2 Pro detection and `hw.perflevel` usage

### ISSUE THREAD

**Issue by vaughajm** [Dr-Noob/cpufetch#183]
[ERROR]: Found invalid cpu_subfamily: 0x00000004
[VERSION]: cpufetch v1.04 (macOS ARM build)
Please, create a new issue with this error message, your smartphone/computer model, the output of 'cpufetch --verbose' and 'cpufetch --debug' on https://github.com/Dr-Noob/cpufetch/issues

                                                            SoC:                 Unknown
                                                            Technology:          Unknown
                                                            CPU 1:
                                                              Microarchitecture: Blizzard
                                                              Max Frequency:     2.800 GHz
                                                              Cores:             4 cores
                                                              Features:          NEON,SHA1,SHA2,AES,CRC32
                                                            CPU 2:
                                                              Microarchitecture: Avalanche
                                                              Max Frequency:     3.500 GHz
                                                              Cores:             4 cores
                                                              Features:          NEON,SHA1,SHA2,AES,CRC32
                                                            Peak Performance:    100.80 GFLOP/s

**Comment by Dr-Noob** [comment]
Thanks for the report, it should be fixed in 36071b8.

**Comment by ThomasKaiser** [comment]
It does work as expected with most recent version:

    mac-ak √ ~ > ./cpufetch 
    
                       ."c.         
                     ,xNMM.         
                    .lMM"           SoC:                 Apple M2 Pro
                    MM*             Technology:          5nm
         .;loddo;:.   olloddol;.    CPU 1:
       cKMMMMMMMMMMNWMMMMMMMMMMM0:    Microarchitecture: Blizzard
     .KMMMMMMMMMMMMMMMMMMMMMMMW*      Max Frequency:     2.800 GHz
     XMMMMMMMMMMMMMMMMMMMMMMMX.       Cores:             8 cores
    ;MMMMMMMMMMMMMMMMMMMMMMMM:        Features:          NEON,SHA1,SHA2,AES,CRC32
    :MMMMMMMMMMMMMMMMMMMMMMMM:      CPU 2:
    .MMMMMMMMMMMMMMMMMMMMMMMMX.       Microarchitecture: Avalanche
     kMMMMMMMMMMMMMMMMMMMMMMMMWd.     Max Frequency:     3.500 GHz
     'XMMMMMMMMMMMMMMMMMMMMMMMMMMk    Cores:             4 cores
      'XMMMMMMMMMMMMMMMMMMMMMMMMK.    Features:          NEON,SHA1,SHA2,AES,CRC32
        kMMMMMMMMMMMMMMMMMMMMMMd    Peak Performance:    806.40 GFLOP/s
         'KMMMMMMMWXXWMMMMMMMk.     
           "cooc"*    "*coo'"       

    mac-ak √ ~ > bi
    Hardware:
    
        Hardware Overview:
    
          Model Name: MacBook Pro
          Model Identifier: Mac14,10
          Model Number: MNW83D/A
          Chip: Apple M2 Pro
          Total Number of Cores: 12 (8 performance and 4 efficiency)
          Memory: 16 GB
          System Firmware Version: 10151.41.12
          OS Loader Version: 8422.141.2.700.1
    
    Software:
    
        System Software Overview:
    
          System Version: macOS 13.6.2 (22G320)
          Kernel Version: Darwin 22.6.0
          Time since boot: 1 day, 8 hours and 3 minutes
    
    17:23  up 1 day,  8:03, 2 users, load averages: 1,90 1,91 2,00

**Comment by vaughajm** [comment]
Looks like it's working now.

Thanks
Joe

**Comment by ThomasKaiser** [comment]
> Looks like it's working now.

Not for me, see above: the 12-core M2 Pro has 4 Blizzard and 8 Avalanche cores but `cpufetch` reports the core count the other way around. 

On your 10-core Mini only 8 cores have been reported when you checked in June. How does it look with most recent version?

**Comment by ThomasKaiser** [comment]
> You’re right it looks like the core counts are reversed

Then reopening the issue would be a way for @Dr-Noob to fix it?

**Comment by Dr-Noob** [comment]
You guys are absolutely right! I didn't know this. It should be fixed now, can you confirm @vaughajm @ThomasKaiser?

**Comment by ThomasKaiser** [comment]
Works for me:

    tk@mac-tk cpufetch % ./cpufetch
    
                       ."c.         
                     ,xNMM.         
                    .lMM"           SoC:                 Apple M1 Pro
                    MM*             Technology:          5nm
         .;loddo;:.   olloddol;.    CPU 1:
       cKMMMMMMMMMMNWMMMMMMMMMMM0:    Microarchitecture: Icestorm
     .KMMMMMMMMMMMMMMMMMMMMMMMW*      Max Frequency:     2.064 GHz
     XMMMMMMMMMMMMMMMMMMMMMMMX.       Cores:             2 cores
    ;MMMMMMMMMMMMMMMMMMMMMMMM:        Features:          NEON,SHA1,SHA2,AES,CRC32
    :MMMMMMMMMMMMMMMMMMMMMMMM:      CPU 2:
    .MMMMMMMMMMMMMMMMMMMMMMMMX.       Microarchitecture: Firestorm
     kMMMMMMMMMMMMMMMMMMMMMMMMWd.     Max Frequency:     3.200 GHz
     'XMMMMMMMMMMMMMMMMMMMMMMMMMMk    Cores:             8 cores
      'XMMMMMMMMMMMMMMMMMMMMMMMMK.    Features:          NEON,SHA1,SHA2,AES,CRC32
        kMMMMMMMMMMMMMMMMMMMMMMd    Peak Performance:    885.25 GFLOP/s
         'KMMMMMMMWXXWMMMMMMMk.     
           "cooc"*    "*coo'"       
    
    tk@mac-tk cpufetch % ./cpufetch -d
    cpufetch v1.04-35-g5e00 (macOS ARM build)
    hw.cpufamily: 0x1B588BB3
    hw.cpusubfamily: 0x00000004
    hw.physicalcpu: 10

**Comment by ThomasKaiser** [comment]
Maybe adding the following to `-d` output to help identyfing core situation with new Apple SoCs?

    tk@mac-tk ~ % /usr/sbin/system_profiler -detailLevel mini SPHardwareDataType
    Hardware:
    
        Hardware Overview:
    
          Model Name: MacBook Pro
          Model Identifier: MacBookPro18,1
          Model Number: MK183D/A
          Chip: Apple M1 Pro
          Total Number of Cores: 10 (8 performance and 2 efficiency)
          Memory: 16 GB
          System Firmware Version: 10151.61.4
          OS Loader Version: 8422.141.2.700.1

And

    ak@mac-ak ~ % /usr/sbin/system_profiler -detailLevel mini SPHardwareDataType
    Hardware:
    
        Hardware Overview:
    
          Model Name: MacBook Pro
          Model Identifier: Mac14,10
          Model Number: MNW83D/A
          Chip: Apple M2 Pro
          Total Number of Cores: 12 (8 performance and 4 efficiency)
          Memory: 16 GB
          System Firmware Version: 10151.61.4
          OS Loader Version: 10151.61.4
    
(while being located below `/usr/sbin/` the tool provides the above output even with only user privileges)

**Comment by ThomasKaiser** [comment]
And another one:

    tk@mac-tk ~ % /usr/sbin/sysctl -a | grep -E "hw.perflevel|cpu.brand_string"
    hw.perflevel0.physicalcpu: 8
    hw.perflevel0.physicalcpu_max: 8
    hw.perflevel0.logicalcpu: 8
    hw.perflevel0.logicalcpu_max: 8
    hw.perflevel0.l1icachesize: 196608
    hw.perflevel0.l1dcachesize: 131072
    hw.perflevel0.l2cachesize: 12582912
    hw.perflevel0.cpusperl2: 4
    hw.perflevel0.name: Performance
    hw.perflevel1.physicalcpu: 2
    hw.perflevel1.physicalcpu_max: 2
    hw.perflevel1.logicalcpu: 2
    hw.perflevel1.logicalcpu_max: 2
    hw.perflevel1.l1icachesize: 131072
    hw.perflevel1.l1dcachesize: 65536
    hw.perflevel1.l2cachesize: 4194304
    hw.perflevel1.cpusperl2: 2
    hw.perflevel1.name: Efficiency
    machdep.cpu.brand_string: Apple M1 Pro

    ak@mac-ak la % /usr/sbin/sysctl -a | grep -E "hw.perflevel|cpu.brand_string"
    hw.perflevel0.physicalcpu: 8
    hw.perflevel0.physicalcpu_max: 8
    hw.perflevel0.logicalcpu: 8
    hw.perflevel0.logicalcpu_max: 8
    hw.perflevel0.l1icachesize: 196608
    hw.perflevel0.l1dcachesize: 131072
    hw.perflevel0.l2cachesize: 16777216
    hw.perflevel0.cpusperl2: 4
    hw.perflevel0.name: Performance
    hw.perflevel1.physicalcpu: 4
    hw.perflevel1.physicalcpu_max: 4
    hw.perflevel1.logicalcpu: 4
    hw.perflevel1.logicalcpu_max: 4
    hw.perflevel1.l1icachesize: 131072
    hw.perflevel1.l1dcachesize: 65536
    hw.perflevel1.l2cachesize: 4194304
    hw.perflevel1.cpusperl2: 4
    hw.perflevel1.name: Efficiency
    machdep.cpu.brand_string: Apple M2 Pro

**Comment by Dr-Noob** [comment]
> And another one:
> 
> ```
> tk@mac-tk ~ % /usr/sbin/sysctl -a | grep -E "hw.perflevel|cpu.brand_string"
> hw.perflevel0.physicalcpu: 8
> hw.perflevel0.physicalcpu_max: 8
> hw.perflevel0.logicalcpu: 8
> hw.perflevel0.logicalcpu_max: 8
> hw.perflevel0.l1icachesize: 196608
> hw.perflevel0.l1dcachesize: 131072
> hw.perflevel0.l2cachesize: 12582912
> hw.perflevel0.cpusperl2: 4
> hw.perflevel0.name: Performance
> hw.perflevel1.physicalcpu: 2
> hw.perflevel1.physicalcpu_max: 2
> hw.perflevel1.logicalcpu: 2
> hw.perflevel1.logicalcpu_max: 2
> hw.perflevel1.l1icachesize: 131072
> hw.perflevel1.l1dcachesize: 65536
> hw.perflevel1.l2cachesize: 4194304
> hw.perflevel1.cpusperl2: 2
> hw.perflevel1.name: Efficiency
> machdep.cpu.brand_string: Apple M1 Pro
> 
> ak@mac-ak la % /usr/sbin/sysctl -a | grep -E "hw.perflevel|cpu.brand_string"
> hw.perflevel0.physicalcpu: 8
> hw.perflevel0.physicalcpu_max: 8
> hw.perflevel0.logicalcpu: 8
> hw.perflevel0.logicalcpu_max: 8
> hw.perflevel0.l1icachesize: 196608
> hw.perflevel0.l1dcachesize: 131072
> hw.perflevel0.l2cachesize: 16777216
> hw.perflevel0.cpusperl2: 4
> hw.perflevel0.name: Performance
> hw.perflevel1.physicalcpu: 4
> hw.perflevel1.physicalcpu_max: 4
> hw.perflevel1.logicalcpu: 4
> hw.perflevel1.logicalcpu_max: 4
> hw.perflevel1.l1icachesize: 131072
> hw.perflevel1.l1dcachesize: 65536
> hw.perflevel1.l2cachesize: 4194304
> hw.perflevel1.cpusperl2: 4
> hw.perflevel1.name: Efficiency
> machdep.cpu.brand_string: Apple M2 Pro
> ```

This is quite interesting, I didn't see this `hw.perflevel` thing when I first implemented the M1 detection. I have created a new branch `i183` that uses this information to fill the number of cores rather than hardcoding it. Could you give it a try @vaughajm @ThomasKaiser? I'm afraid though that this might not be implemented in all macOS versions (haven't seen any information regarding this so far).

**Comment by ThomasKaiser** [comment]
>  I didn't see this `hw.perflevel` thing when I first implemented the M1 detection.

These sysctls exist for [quite some time](https://github.com/google/benchmark/issues/1310) now. :)

**Comment by Dr-Noob** [comment]
> ```
> tk@mac-tk cpufetch % sw_vers
> ProductName:		macOS
> ProductVersion:		13.6.3
> BuildVersion:		22G436
> 
> tk@mac-tk cpufetch % ./cpufetch -d                                        
> cpufetch v1.04-37-g0f6a (macOS ARM build)
> hw.cpufamily: 0x1B588BB3
> hw.cpusubfamily: 0x00000004
> hw.physicalcpu: 10
> 
> tk@mac-tk cpufetch % ./cpufetch   
> 
>                    ."c.         
>                  ,xNMM.         
>                 .lMM"           SoC:                 Apple M1 Pro
>                 MM*             Technology:          5nm
>      .;loddo;:.   olloddol;.    CPU 1:
>    cKMMMMMMMMMMNWMMMMMMMMMMM0:    Microarchitecture: Icestorm
>  .KMMMMMMMMMMMMMMMMMMMMMMMW*      Max Frequency:     2.064 GHz
>  XMMMMMMMMMMMMMMMMMMMMMMMX.       Cores:             2 cores
> ;MMMMMMMMMMMMMMMMMMMMMMMM:        Features:          NEON,SHA1,SHA2,AES,CRC32
> :MMMMMMMMMMMMMMMMMMMMMMMM:      CPU 2:
> .MMMMMMMMMMMMMMMMMMMMMMMMX.       Microarchitecture: Firestorm
>  kMMMMMMMMMMMMMMMMMMMMMMMMWd.     Max Frequency:     3.200 GHz
>  'XMMMMMMMMMMMMMMMMMMMMMMMMMMk    Cores:             8 cores
>   'XMMMMMMMMMMMMMMMMMMMMMMMMK.    Features:          NEON,SHA1,SHA2,AES,CRC32
>     kMMMMMMMMMMMMMMMMMMMMMMd    Peak Performance:    885.25 GFLOP/s
>      'KMMMMMMMWXXWMMMMMMMk.     
>        "cooc"*    "*coo'"       
> ```
> 
> And
> 
> ```
> mac-ak √ ~ > sw_vers 
> ProductName:		macOS
> ProductVersion:		14.2.1
> BuildVersion:		23C71
> 
> mac-ak √ ~ > /tmp/cpufetch
> 
>                    ."c.         
>                  ,xNMM.         
>                 .lMM"           SoC:                 Apple M2 Pro
>                 MM*             Technology:          5nm
>      .;loddo;:.   olloddol;.    CPU 1:
>    cKMMMMMMMMMMNWMMMMMMMMMMM0:    Microarchitecture: Blizzard
>  .KMMMMMMMMMMMMMMMMMMMMMMMW*      Max Frequency:     2.800 GHz
>  XMMMMMMMMMMMMMMMMMMMMMMMX.       Cores:             4 cores
> ;MMMMMMMMMMMMMMMMMMMMMMMM:        Features:          NEON,SHA1,SHA2,AES,CRC32
> :MMMMMMMMMMMMMMMMMMMMMMMM:      CPU 2:
> .MMMMMMMMMMMMMMMMMMMMMMMMX.       Microarchitecture: Avalanche
>  kMMMMMMMMMMMMMMMMMMMMMMMMWd.     Max Frequency:     3.500 GHz
>  'XMMMMMMMMMMMMMMMMMMMMMMMMMMk    Cores:             8 cores
>   'XMMMMMMMMMMMMMMMMMMMMMMMMK.    Features:          NEON,SHA1,SHA2,AES,CRC32
>     kMMMMMMMMMMMMMMMMMMMMMMd    Peak Performance:    1.08 TFLOP/s
>      'KMMMMMMMWXXWMMMMMMMk.     
>        "cooc"*    "*coo'"       
> ```
> 
> BTW: my main reasoning for using the information provided by `sysctl` was adding this to `-d` output since once a future M4 [Pro|Max|Ultra|Turbo|Whatever] is out somebody will open up a new issue here and then having this information at hand without having to rely on early reviews or Apple announcements might be an improvement?

Yeah absolutely. Fetching the information is always the way to go, but I just didn't know this existed. I'll merge this because sysctl simplifies everything a lot. I'll also this to the `-d` output. Thanks for your feedback, this is definitely an improvement in the Apple SoC detection :+1:
