### ISSUE TITLE
AMD Ryzen 7 7735HS not fully analyzed

### ISSUE THREAD

**Issue by ajay6915** [Dr-Noob/cpufetch#184]
CPU fetch result:
Name: AMD Ryzen 7 7735HS with Radeon Graphics 
Microarchitecture: Unknown
Technology:  Unknown
Max Frequency: 4.828 GHz
Cores: 8 cores (16 threads)
AVX: AVX,AVX2
FMA: FMA3
L1i Size: 32KB (256KB Total)
L1d Size: 32KB (256KB Total)
L2 Size: 512KB (4MB Total)
L3 Size: 16MB
Peak Performance:  617.98 GFLOP/s

Debug report:
cpufetch v1.02 (Linux x86_64 build)
AMD Ryzen 7 7735HS with Radeon Graphics 
- Max standard level: 0x00000010
- Max extended level: 0x80000023
- AMD topology extensions: 1
- CPUID dump: 0x00A40F41

**Comment by Dr-Noob** [comment]
It should work with the last release of cpufetch (`v1.04`). Please check and re-open the issue if still does not work.
