### ISSUE TITLE
Ryzen 7 7840HS is not recognized

### ISSUE THREAD

**Issue by darkbuck** [Dr-Noob/cpufetch#187]
- Ryzen 7 7840HS
- Ubuntu 22.04
- cpuid
[cpuid.7840hs.txt](https://github.com/Dr-Noob/cpufetch/files/12268093/cpuid.7840hs.txt)
- cpuid --debug
[cpuid.7840hs.debug.txt](https://github.com/Dr-Noob/cpufetch/files/12268092/cpuid.7840hs.debug.txt)

**Comment by darkbuck** [comment]
support fo reference is posted @ https://github.com/darkbuck/cpufetch/tree/7840hs

**Comment by Dr-Noob** [comment]
Thanks for reporting! I just pushed a new commit with this cpuid.
