### ISSUE TITLE
rockchip rk3588S soc not recognised

### ISSUE THREAD

**Issue by Im-0xea** [Dr-Noob/cpufetch#188]
https://github.com/Im-0xea/cpufetch

**Comment by Im-0xea** [comment]
efuse does not seam to be there for rk3588S, that is why im reading from otp

sorry for implenting it for you, I did not read your contributing guidlines before fixing this

**Comment by Dr-Noob** [comment]
Interesting! Thanks for your contribution, I just pushed a similar commit. Can you please confirm it also works in your machine?

**Comment by Im-0xea** [comment]
Hi!,

I currently don't have my rk3588S setup for testing it again

In my opinion there is no need for testing though considering your commit differs to mine in exactly one space for formating
