### ISSUE TITLE
MacBook Pro M2 Pro: [ERROR]: Found invalid cpu_subfamily: 0x00000004

### ISSUE THREAD

**Issue by sm-moshi** [Dr-Noob/cpufetch#191]
Hi, 

just want to hand this in. :)

`❯ cpufetch --verbose`
`[ERROR]: Found invalid cpu_subfamily: 0x00000004`
`[VERSION]: cpufetch v1.04 (macOS ARM build)`
`[WARNING]: SoC detection failed using cpu_subfamily`

<img width="906" alt="Screenshot 2023-08-29 at 23 57 08" src="https://github.com/Dr-Noob/cpufetch/assets/12695314/38d7ddf7-4a00-43df-8d28-b3e98ef5088a">

`❯ cpufetch --debug`
`[ERROR]: Found invalid cpu_subfamily: 0x00000004`
`[VERSION]: cpufetch v1.04 (macOS ARM build)`
`cpufetch v1.04 (macOS ARM build)`

<img width="906" alt="Screenshot 2023-08-29 at 23 57 38" src="https://github.com/Dr-Noob/cpufetch/assets/12695314/15843ce3-fb1d-4eff-9110-1b231af54d94">

Model: 
<img width="392" alt="Screenshot 2023-08-29 at 23 52 07" src="https://github.com/Dr-Noob/cpufetch/assets/12695314/4e382d7e-dbe0-48e8-b4d3-4520fdd96381">

I hope I can be of any help with this issue. I'll try to take a look at the code and try to figure out a way by myself, but can't promise anything, since I'm not a Dev, but a SysAdmin.

Greetings,
Stuart

**Comment by Dr-Noob** [comment]
No worries, just reporting is more than enough so that I can fix it. This is related to #190 and, as I mentioned there, it should be fixed now. Can you please confirm?

**Comment by Dr-Noob** [comment]
Closing as completed (see proof in #203)
