### ISSUE TITLE
Unknown microarchitecture detected on M1

### ISSUE THREAD

**Issue by dherniko** [Dr-Noob/cpufetch#197]
Can't find the info of linux VM on M1 Arm CPU
`[ERROR]: Unknown microarchitecture detected: IM=0x00000061 P=0x00000000 V=0x00000000 R=0x00000000
Please, create a new issue with this error message, your smartphone/computer model, the output of 'cpufetch' and 'cpufetch --debug' on https://github.com/Dr-Noob/cpufetch/issues
cpufetch v1.01 (Linux ARM build)
[Core 0] 0x610F0000 -1 MHz
[Core 1] 0x610F0000 -1 MHz`

**Comment by Dr-Noob** [comment]
Being unable to detect the CPU under a VM (and especially in the case of a VM running on the M1) is the expected behavior. The VM modifies the CPU information and returns invalid information (e.g., `0x610F0000`) so there is nothing that a user program like cpufetch can do about it.
