### ISSUE TITLE
Google Tensor G3 (Pixel 8/8 Pro) Support

### ISSUE THREAD

**Issue by Relms12345** [Dr-Noob/cpufetch#198]
It reports the A715 and X3 cores as unknown. Debug and Verbose screenshots as attached.
(Device is rooted hence sudo)

![image](https://github.com/Dr-Noob/cpufetch/assets/57138119/2443247f-b49a-46db-901e-75a1a172dfbe)

**Comment by Dr-Noob** [comment]
Thanks for reporting the issue. I have pushed a few patches, so it should work now

**Comment by Relms12345** [comment]
Can confirm it works now. Thanks!
