### ISSUE TITLE
[ERROR]: Unknown microarchitecture detected: M=0x0000000A EM=0x0000000B F=0x00000006 EF=0x00000000 S=0x00000003

### ISSUE THREAD

**Issue by markfelt** [Dr-Noob/cpufetch#223]
[ERROR]: Unknown microarchitecture detected: M=0x0000000A EM=0x0000000B F=0x00000006 EF=0x00000000 S=0x00000003
[VERSION]: cpufetch v1.04 (Windows x86_64 build)
Please, create a new issue with this error message, the output of 'cpufetch' and 'cpufetch --debug' on https://github.com/Dr-Noob/cpufetch/issues
[ERROR]: Unknown microarchitecture detected: M=0x0000000A EM=0x0000000B F=0x00000006 EF=0x00000000 S=0x00000003
[VERSION]: cpufetch v1.04 (Windows x86_64 build)
Please, create a new issue with this error message, the output of 'cpufetch' and 'cpufetch --debug' on https://github.com/Dr-Noob/cpufetch/issues
[ERROR]: Failed binding the process to CPU 12
[VERSION]: cpufetch v1.04 (Windows x86_64 build)
[ERROR]: Failed to retrieve topology from APIC, assumming default values...

[VERSION]: cpufetch v1.04 (Windows x86_64 build)
[ERROR]: Found invalid process: '0'
[VERSION]: cpufetch v1.04 (Windows x86_64 build)
Please, create a new issue with this error message, the output of 'cpufetch' and 'cpufetch --debug' on https://github.com/Dr-Noob/cpufetch/issues

                                                              Name:                13th Gen Intel(R) Core(TM) i7-1365U
                                                              Hypervisor:          Microsoft Hyper-V
                                                              Microarchitecture:   Unknown
                                                              Technology:          Unknown
                                                              P-cores:
                                                                Max Frequency:     Unknown
                                                                Cores:             6 cores (12 threads)
                                                                AVX:               AVX,AVX2
                                                                FMA:               FMA3
                                                                L1i Size:          32KB (320KB Total)
                                                                L1d Size:          48KB (480KB Total)
                                                                L2 Size:           1.25MB (5MB Total)
                                                              E-cores:
                                                                Max Frequency:     Unknown
                                                                Cores:             Unknown
                                                                AVX:               AVX,AVX2
                                                                FMA:               FMA3
                                                                L1i Size:          64KB (12MB Total)
                                                                L1d Size:          32KB (6MB Total)
                                                                L2 Size:           2MB (384MB Total)
                                                              L3 Size:             12MB
                                                              Peak Performance:    Unknown

[ERROR]: Unknown microarchitecture detected: M=0x0000000A EM=0x0000000B F=0x00000006 EF=0x00000000 S=0x00000003
[VERSION]: cpufetch v1.04 (Windows x86_64 build)
Please, create a new issue with this error message, the output of 'cpufetch' and 'cpufetch --debug' on https://github.com/Dr-Noob/cpufetch/issues
[ERROR]: Unknown microarchitecture detected: M=0x0000000A EM=0x0000000B F=0x00000006 EF=0x00000000 S=0x00000003
[VERSION]: cpufetch v1.04 (Windows x86_64 build)
Please, create a new issue with this error message, the output of 'cpufetch' and 'cpufetch --debug' on https://github.com/Dr-Noob/cpufetch/issues
[ERROR]: Failed binding the process to CPU 12
[VERSION]: cpufetch v1.04 (Windows x86_64 build)
[ERROR]: Failed to retrieve topology from APIC, assumming default values...

[VERSION]: cpufetch v1.04 (Windows x86_64 build)
cpufetch v1.04 (Windows x86_64 build)
13th Gen Intel(R) Core(TM) i7-1365U
- Hypervisor: Microsoft Hyper-V
- Max standard level: 0x00000020
- Max extended level: 0x80000008
- Hybrid Flag: 1
- CPUID dump: 0x000B06A3

**Comment by Dr-Noob** [comment]
Please update to [cpufetch v1.05](https://github.com/Dr-Noob/cpufetch/releases/tag/v1.05)
