### ISSUE TITLE
[ERROR]: Found invalid cpu_family: 0x5F4DEA93 (M3 pro macbook pro)

### ISSUE THREAD

**Issue by Talhamehar007** [Dr-Noob/cpufetch#225]
When running the command cpufetch on the new M3 pro macbook pro, it gives this error:

```
× cpufetch 
[ERROR]: Found invalid cpu_family: 0x5F4DEA93
[VERSION]: cpufetch v1.04 (macOS ARM build)
Please, create a new issue with this error message, your smartphone/computer model, the output of 'cpufetch --verbose' and 'cpufetch --debug' on https://github.com/Dr-Noob/cpufetch/issues
```
Running MacOS version 14.3

The command gives the same error when running 'cpufetch --verbose' and 'cpufetch --debug'

**Comment by Dr-Noob** [comment]
Please update to [cpufetch v1.05](https://github.com/Dr-Noob/cpufetch/releases/tag/v1.05)
