### ISSUE TITLE
FreeBSD haven't got alternative way to get CPU frequency in case of cpuid failure

### ISSUE THREAD

**Issue by er2off** [Dr-Noob/cpufetch#233]
So, everything was said in title, I implemented this in #232 but pull requests are automatically closes.
This also could potentially happen in macOS so it also have fallback.

**Comment by Dr-Noob** [comment]
In general I do not accept patches, but yours seems to be very interesting. Could you please submit it again? I can reopen the PR once you submit it, but it seems like you have deleted the source branch so I cannot do that right now.

**Comment by Dr-Noob** [comment]
Awesome, thanks. Let's continue the conversation in the PR.
