### ISSUE TITLE
cpufetch doesn't understand the VirtualBox Hypervisor

### ISSUE THREAD

**Issue by diekemjm** [Dr-Noob/cpufetch#235]
When running Ubuntu 24.04 LTS under VirtualBox 7.0.14, I see:

azure 150} cpufetch
[ERROR]: Unknown hypervisor vendor: 'VBoxVBoxVBox'
[VERSION]: cpufetch v1.05-6-g2976 (Linux x86 / x86_64 build)
Please, create a new issue with this error message, the output of 'cpufetch' and 'cpufetch --debug' on https://github.com/Dr-Noob/cpufetch/issues

                                                   Name:         12th Gen Intel(
                                                   Hypervisor:   Unknown
  MMM                 oddl                   MMN   uArch:        Alder Lake
  MMM                 dMMN                   MMN   Technology:   10nm
  ...  ....   ...     dMMM..      .cc.       NMN   Max Freq:     Unknown
  MMM  :MMMdWMMMMMX.  dMMMMM,  .XMMMMMMNo    MMN   Cores:        8 cores
  MMM  :MMMp    dMMM  dMMX   .NMW      WMN.  MMN   AVX:          AVX,AVX2
  MMM  :MMM      WMM  dMMK   kMMXooooooNMMx  MMN   FMA:          No
  MMM  :MMM      NMM  dMMK   dMMX            MMN   L1i Size:     32KB (256KB Tot
  MMM  :MMM      NMM  dMMMoo  OMM0....:Nx.   MMN   L1d Size:     48KB (384KB Tot
  MMM  :WWW      XWW   lONMM   'xXMMMMNOc    MMN   L2 Size:      1.25MB (10MB To
                                                   L3 Size:      30MB (240MB Tot
                                                   Peak Perf.:   Unknown

azure 151} cpufetch --debug
[ERROR]: Unknown hypervisor vendor: 'VBoxVBoxVBox'
[VERSION]: cpufetch v1.05-6-g2976 (Linux x86 / x86_64 build)
Please, create a new issue with this error message, the output of 'cpufetch' and 'cpufetch --debug' on https://github.com/Dr-Noob/cpufetch/issues
cpufetch v1.05-6-g2976 (Linux x86 / x86_64 build)
12th Gen Intel(R) Core(TM) i9-12950HX
- Hypervisor: Unknown
- Max standard level: 0x00000016
- Max extended level: 0x80000008
- Hybrid Flag: 0
- CPUID dump: 0x00090672

Ref: https://www.virtualbox.org/

**Comment by Dr-Noob** [comment]
Weird, I assumed it already supported VirtualBox, but seems like it didn't! I have added support for it, can you confirm if it works now?
