### ISSUE TITLE
unknown microarchitecture (i5 12400f)

### ISSUE THREAD

**Issue by kamile320** [Dr-Noob/cpufetch#236]
output after "cpufetch":
[ERROR]: Unknown microarchitecture detected: M=0x00000007 EM=0x00000009 F=0x00000006 EF=0x00000000 S=0x00000005
Please, create a new issue with this error message, the output of 'cpufetch' and 'cpufetch --debug' on https://github.com/Dr-Noob/cpufetch/issues
[ERROR]: Found invalid process: '0'
Please, create a new issue with this error message, the output of 'cpufetch' and 'cpufetch --debug' on https://github.com/Dr-Noob/cpufetch/issues

+logo

output after "cpufetch --debug":
[ERROR]: Unknown microarchitecture detected: M=0x00000007 EM=0x00000009 F=0x00000006 EF=0x00000000 S=0x00000005
Please, create a new issue with this error message, the output of 'cpufetch' and 'cpufetch --debug' on https://github.com/Dr-Noob/cpufetch/issues
cpufetch v1.01 (Linux x86_64 build)
12th Gen Intel(R) Core(TM) i5-12400F
- Max standard level: 0x00000020
- Max extended level: 0x80000008
- CPUID dump: 0x00090675

OS - Linux Mint 21.3
CPU - intel i5 12400f

![cpu](https://github.com/Dr-Noob/cpufetch/assets/156579182/1fe7270e-5cdc-43b6-83e2-33d2cc07bc49)

**Comment by Dr-Noob** [comment]
You are running cpufetch v1.01 whereas the current version is v1.05, please update to the latest version. See how to do this [here](https://github.com/Dr-Noob/cpufetch?tab=readme-ov-file#2-installation).
