### ISSUE TITLE
gpufetch

### ISSUE THREAD

**Issue by Dr-Noob** [Dr-Noob/cpufetch#24]
For a future project, developing a cpufetch like tool for GPU could be interesting.

For NVIDIA GPUs, I know that CUDA can give you any kind of details. For radeon and integrated GPUs (Intel, for example), I don't know how to approach it.

**Comment by slinkouswasalreadytaken** [comment]
Would definitely like to see this.

**Comment by erkinalp** [comment]
> For NVIDIA GPUs, I know that CUDA can give you any kind of details.

For AMD GPUs, we have HIP as the equivalent of CUDA, which could help you retrieve similar level of detail.

**Comment by Dr-Noob** [comment]
Thanks for your suggestion. Yeah, I knew about HIP and ROCm in AMD GPUs. 

The main problem I see right now is that I do not have access to any AMD GPU, so testing would be impossible. Besides, Intel iGPU looks much harder...I will think about that whenever I have enough time go start working on this project (this summer, I hope...)

**Comment by MonAaraj** [comment]
I do have an AMD GPU that I could test for you, but I doubt it's exactly what you're looking for. I also have an Intel iGPU as well.

**Comment by Dr-Noob** [comment]
Thanks for your offer! 

Right now I'm not sure what I will be looking for, but I guess that any dedicated AMD GPU (Radeon RX) should be enough.

**Comment by fP4rad0x** [comment]
Very interesting idea, looking forward to it.

**Comment by MonAaraj** [comment]
My dedicated GPU is an AMD Radeon R7 M260. My integrated Intel GPU is a Mesa DRI Intel(R) HD Graphics 4400 (HSW GT2).

The above information was all according to `glxinfo -B`.

**Comment by erkinalp** [comment]
My dedicated GPU is ASUS ROG-STRIX RX 5500 XT. I would be more than happy to help you.

**Comment by Dr-Noob** [comment]
Thank you guys, I hope that it will be much easier with your help. I will start the project soon, so stay tuned!

**Comment by Shadow2302** [comment]
In case you need an AMD iGPU, got a Ryzen 5 3500U with Vega 8

**Comment by alou-S** [comment]
My list of devices:
Intel® HD Graphics for Previous Generation Intel® Processors (i3 540)
Nviida 210
Intel® HD Graphics 520 (i7 6500U)

Phones:
Samsung M01 (MSM8937 with Adreno 505) {rooted}
Samsung M21 (Exynos 9611 with Mali-G72 MP3)

Free to help.

**Comment by Dr-Noob** [comment]
Good news! A first version of gpufetch is already available on https://github.com/Dr-Noob/gpufetch. Currently, it only works with NVIDIA GPUs and Linux. I hope you guys like it.

Regarding AMD support, I've done a bit of research and I have found that [ROCm has little support for AMD GPUs](https://github.com/RadeonOpenCompute/ROCm#hardware-and-software-support). Among thousand of cards, they say "yeah, a few of them should work, and the rest of 95% of GPUs...they may or may not work". This scares me because it would be really easy to say that gpufetch does not work for my GPU when it's actually ROCm's fault. Anyway, if anybody is willing to give me ssh access to a machine with an AMD GPU that is supported by ROCm, I will work on it (only during this month). I would prefer that the machine has all the software and drivers installed, but I will take care of that if it is not the case. Any volunteers? @erkinalp

I will close this issue soon. If you have anything to say about the new project, please use the gpufetch issues. For those who are going to give it a try; it's a new project, there will be a lot of issues and broken things...so be cool 😅

**Comment by Shadow2302** [comment]
The Ryzen iGPU on my laptop is a GFX9, and as the readme file on ROCm says, it does support GFX9, so if you need to, next week i’d be available to share access to my laptop via ssh

**Comment by erkinalp** [comment]
@Dr-Noob ROCm works fine on my card, but I will have to recompile it from scratch as I am currently using 21.04.

**Comment by Dr-Noob** [comment]
> The Ryzen iGPU on my laptop is a GFX9, and as the readme file on ROCm says, it does support GFX9, so if you need to, next week i’d be available to share access to my laptop via ssh

The documentation is a bit confusing, at least for me. It says: "_ROCm officially supports AMD GPUs that use following chips: GFX9_" but later says "_The integrated GPUs in AMD APUs are not officially supported targets for ROCm_", so it is not very clear to me if your iGPU is supported or not. Do you have installed ROCm? Can you run any basic code, like https://github.com/ROCm-Developer-Tools/HIP-Examples/blob/master/HIP-Examples-Applications/HelloWorld/HelloWorld.cpp?

**Comment by Dr-Noob** [comment]
> @Dr-Noob ROCm works fine on my card, but I will have to recompile it from scratch as I am currently using 21.04.

Good to know. If you are willing to recompile ROCm, it should be enough to allow me to make the AMD GPU port.

**Comment by Shadow2302** [comment]
> > The Ryzen iGPU on my laptop is a GFX9, and as the readme file on ROCm says, it does support GFX9, so if you need to, next week i’d be available to share access to my laptop via ssh
> 
> The documentation is a bit confusing, at least for me. It says: "_ROCm officially supports AMD GPUs that use following chips: GFX9_" but later says "_The integrated GPUs in AMD APUs are not officially supported targets for ROCm_", so it is not very clear to me if your iGPU is supported or not. Do you have installed ROCm? Can you run any basic code, like https://github.com/ROCm-Developer-Tools/HIP-Examples/blob/master/HIP-Examples-Applications/HelloWorld/HelloWorld.cpp?

Sorry for not answering, was in another country on holidays. 
Right now I don’t have it installed, but I’ll install it this evening and will try to run the code

**Comment by Dr-Noob** [comment]
I'm closing the issue as `gpufetch` is a separate project now, and this issue is not useful here anymore. 

If anybody is willing to help with the AMD thing, please see [issue 7](https://github.com/Dr-Noob/gpufetch/issues/7). Thanks!
