### ISSUE TITLE
README.md. RISC-V example screenshot attached

### ISSUE THREAD

**Issue by RogerHardiman** [Dr-Noob/cpufetch#241]
Hi
cpufetch works great on my StarFive VisionFive2 SBC so took a screenshot to add to the README as Section 3.4
Noticed in the Examples of README.md there was no RISC-V example so made a fork and added one in.

The README.md and picture can be found here
   https://github.com/Dr-Noob/cpufetch/compare/master...RogerHardiman:cpufetch:additions

![visionfive2](https://github.com/Dr-Noob/cpufetch/assets/10171169/7db53bce-cb98-4ba5-938d-d342efdc4aa5)

Thanks for a great utility, found via Thomas Kaiser's SBC project.

**Comment by Dr-Noob** [comment]
Sorry for the late reply. In order to mantain a similar look and feel trough the entire README, I have used your screenshot to recreate another one with the same background color. This way it looks better. Thanks for the screenshot and for the idea!

**Comment by RogerHardiman** [comment]
Many thanks for merging in. 
and has reminded me I've got a load of PRs on some of my own projects I need to review and merge in.
