### ISSUE TITLE
Intel(R) Core(TM) i5-14600K [[ERROR]: Unknown microarchitecture detected: M=0x00000007 EM=0x0000000B F=0x00000006 EF=0x00000000 S=0x00000001]

### ISSUE THREAD

**Issue by human-unidentified** [Dr-Noob/cpufetch#242]
[ERROR]: Unknown microarchitecture detected: M=0x00000007 EM=0x0000000B F=0x00000006 EF=0x00000000 S=0x00000001
Please, create a new issue with this error message, the output of 'cpufetch' and 'cpufetch --debug' on https://github.com/Dr-Noob/cpufetch/issues
[ERROR]: Found invalid process: '0'
Please, create a new issue with this error message, the output of 'cpufetch' and 'cpufetch --debug' on https://github.com/Dr-Noob/cpufetch/issues

Name:              Intel(R) Core(TM) i5-14600K
Hypervisor:        Microsoft Hyper-V
Microarchitecture: Unknown
Technology:        Unknown
Max Frequency:     Unknown
Cores:             10 cores (20 threads)
AVX:               AVX,AVX2
FMA:               FMA3
L1i Size:          32KB (320KB Total)
L1d Size:          48KB (480KB Total)
L2 Size:           2MB (20MB Total)
L3 Size:           24MB
Peak Performance:  Unknown
-------
[ERROR]: Unknown microarchitecture detected: M=0x00000007 EM=0x0000000B F=0x00000006 EF=0x00000000 S=0x00000001
Please, create a new issue with this error message, the output of 'cpufetch' and 'cpufetch --debug' on https://github.com/Dr-Noob/cpufetch/issues
cpufetch v1.01 (Linux x86_64 build)
Intel(R) Core(TM) i5-14600K
- Hypervisor: Microsoft Hyper-V
- Max standard level: 0x0000001C
- Max extended level: 0x80000008
- CPUID dump: 0x000B0671

**Comment by Dr-Noob** [comment]
You are running cpufetch v1.01 whereas the current version is v1.05, please update to the latest version. See how to do this [here](https://github.com/Dr-Noob/cpufetch?tab=readme-ov-file#2-installation).
