### ISSUE TITLE
Hygon CPU is not supported.

### ISSUE THREAD

**Issue by RevySR** [Dr-Noob/cpufetch#244]
```
cpufetch --debug
[ERROR]: Unknown CPU vendor: HygonGenuine
```

**Comment by RevySR** [comment]
```
cat /proc/cpuinfo
processor	: 0
vendor_id	: HygonGenuine
cpu family	: 24
model		: 1
model name	: Hygon C86 3250  8-core Processor
stepping	: 1
microcode	: 0x80901047
cpu MHz		: 1600.000
cache size	: 512 KB
physical id	: 0
siblings	: 16
core id		: 0
cpu cores	: 8
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb hw_pstate ssbd ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 xsaves clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif overflow_recov succor smca sme sev sev_es
bugs		: sysret_ss_attrs null_seg spectre_v1 spectre_v2 spec_store_bypass retbleed smt_rsb srso
bogomips	: 5589.57
TLB size	: 2560 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 48 bits physical, 48 bits virtual
power management: ts ttp tm hwpstate eff_freq_ro [13] [14]
```

**Comment by Dr-Noob** [comment]
Wow, this is very interesting! I have added preeliminary support for this in the `hygon` branch. Could try it? 

Also, could you post the output of `./cpufetch --debug`? That would very helpful.

**Comment by RevySR** [comment]
```
./cpufetch --debug
[ERROR]: Unknown microarchitecture detected: M=0x1 EM=0x0 F=0xF EF=0x9 S=0x1
[VERSION]: cpufetch v1.05-11-g9018 (Linux x86 / x86_64 build)
Please, create a new issue with this error message, the output of 'cpufetch' and 'cpufetch --debug' on https://github.com/Dr-Noob/cpufetch/issues
cpufetch v1.05-11-g9018 (Linux x86 / x86_64 build)
Hygon C86 3250 8-core Processor
- Max standard level: 0x0000000D
- Max extended level: 0x8000001F
- CPUID dump: 0x00900F11
```

**Comment by Dr-Noob** [comment]
> ```
> ./cpufetch --debug
> [ERROR]: Unknown microarchitecture detected: M=0x1 EM=0x0 F=0xF EF=0x9 S=0x1
> [VERSION]: cpufetch v1.05-11-g9018 (Linux x86 / x86_64 build)
> Please, create a new issue with this error message, the output of 'cpufetch' and 'cpufetch --debug' on https://github.com/Dr-Noob/cpufetch/issues
> cpufetch v1.05-11-g9018 (Linux x86 / x86_64 build)
> Hygon C86 3250 8-core Processor
> - Max standard level: 0x0000000D
> - Max extended level: 0x8000001F
> - CPUID dump: 0x00900F11
> ```

Thanks for the feedback, looking good. I have pushed another commit, could you give it a try again?

**Comment by RevySR** [comment]
> > ```
> > ./cpufetch --debug
> > [ERROR]: Unknown microarchitecture detected: M=0x1 EM=0x0 F=0xF EF=0x9 S=0x1
> > [VERSION]: cpufetch v1.05-11-g9018 (Linux x86 / x86_64 build)
> > Please, create a new issue with this error message, the output of 'cpufetch' and 'cpufetch --debug' on https://github.com/Dr-Noob/cpufetch/issues
> > cpufetch v1.05-11-g9018 (Linux x86 / x86_64 build)
> > Hygon C86 3250 8-core Processor
> > - Max standard level: 0x0000000D
> > - Max extended level: 0x8000001F
> > - CPUID dump: 0x00900F11
> > ```
> 
> Thanks for the feedback, looking good. I have pushed another commit, could you give it a try again?

<img width="1484" alt="image" src="https://github.com/Dr-Noob/cpufetch/assets/13116853/ce8c05d6-06ee-4eae-ad4f-92d91e376043">

**Comment by Dr-Noob** [comment]
Nice! The manufacturing process is not public I think (at least I could not find it online). Any feedback or comment? Otherwise I'll merge it into master :+1:

**Comment by RevySR** [comment]
> Nice! The manufacturing process is not public I think (at least I could not find it online). Any feedback or comment? Otherwise I'll merge it into master 👍

I can't find any relevant information.

**Comment by Dr-Noob** [comment]
Merged into main, thanks for the feedback!
