### ISSUE TITLE
N100 - Intel - CPU is not supported.

### ISSUE THREAD

**Issue by curyjorge98** [Dr-Noob/cpufetch#247]
Hi,

Message:

me@tuxedo:~$ cpufetch 
[ERROR]: Unknown microarchitecture detected: M=0x0000000E EM=0x0000000B F=0x00000006 EF=0x00000000 S=0x00000000
Please, create a new issue with this error message, the output of 'cpufetch' and 'cpufetch --debug' on https://github.com/Dr-Noob/cpufetch/issues
[ERROR]: Found invalid process: '0'
Please, create a new issue with this error message, the output of 'cpufetch' and 'cpufetch --debug' on https://github.com/Dr-Noob/cpufetch/issues

                   .#################.          
              .####                   ####.     Name:       Intel(R) N100
          .##                             ###   uArch:      Unknown
       ##                          :##     ###  Technology: Unknown
    #                ##            :##      ##  Max Freq:   3.400 GHz
  ##   ##  ######.   ####  ######  :##      ##  Cores:      4 cores
 ##    ##  ##:  ##:  ##   ##   ### :##     ###  AVX:        AVX,AVX2
##                                             L2 Size:    2MB
  ###.                         ..o####.         L3 Size:    6MB
   ######oo...         ..oo#######              Peak Perf.: 217.60 GFLOP

@tuxedo:~$ cpufetch --debug
[ERROR]: Unknown microarchitecture detected: M=0x0000000E EM=0x0000000B F=0x00000006 EF=0x00000000 S=0x00000000
Please, create a new issue with this error message, the output of 'cpufetch' and 'cpufetch --debug' on https://github.com/Dr-Noob/cpufetch/issues
cpufetch v1.01 (Linux x86_64 build)
Intel(R) N100
- Max standard level: 0x00000020
- Max extended level: 0x80000008
- CPUID dump: 0x000B06E0

Thanks,

**Comment by Dr-Noob** [comment]
Please [install the latest version of cpufetch](https://github.com/Dr-Noob/cpufetch?tab=readme-ov-file#2-installation), you are running v1.01 while we are at v1.05.
