### ISSUE TITLE
[ERROR]: Unknown microarchitecture detected: M=0x00000001 EM=0x00000006 F=0x0000000F EF=0x0000000A S=0x00000002

### ISSUE THREAD

**Issue by SoccyUwU** [Dr-Noob/cpufetch#252]
PS C:\Users\Socc Puppet> cpufetch -v
[ERROR]: Unknown microarchitecture detected: M=0x00000001 EM=0x00000006 F=0x0000000F EF=0x0000000A S=0x00000002
Please, create a new issue with this error message and the output of 'cpufetch --debug' on https://github.com/Dr-Noob/cpufetch/issues
[WARNING]: Can't read frequency information from cpuid (needed level is 0x00000016, max is 0x0000000D)
[ERROR]: Found invalid process: '0'
Please, create a new issue with this error message and the output of 'cpufetch --debug' on https://github.com/Dr-Noob/cpufetch/issues

PS C:\Users\Socc Puppet> cpufetch --debug
[ERROR]: Unknown microarchitecture detected: M=0x00000001 EM=0x00000006 F=0x0000000F EF=0x0000000A S=0x00000002
Please, create a new issue with this error message and the output of 'cpufetch --debug' on https://github.com/Dr-Noob/cpufetch/issues
cpufetch v1.00 (Windows x86_64 build)
AMD Ryzen 9 7945HX with Radeon Graphics
- Hypervisor: Microsoft Hyper-V
- Max standard level: 0x0000000D
- Max extended level: 0x80000026
- AMD topology extensions: 1
- CPUID dump: 0x00A60F12

**Comment by Dr-Noob** [comment]
You are running an old version of cpufetch. The last version is v1.05, please update and try again (you can find more information [here](https://github.com/Dr-Noob/cpufetch?tab=readme-ov-file#2-installation)).
