### ISSUE TITLE
Unknown uArch and Technology for AMD Ryzen 7 6800HS with Radeon Graphics

### ISSUE THREAD

**Issue by jesustejerina** [Dr-Noob/cpufetch#254]
[ERROR]: Unknown microarchitecture detected: M=0x00000004 EM=0x00000004 F=0x0000000F EF=0x0000000A S=0x00000001

[ERROR]: Unknown microarchitecture detected: M=0x00000004 EM=0x00000004 F=0x0000000F EF=0x0000000A S=0x00000001

I have AMD Ryzen 7 6800HS with Radeon Graphics.

uArch: Unknown
Technology: Unknown

![caca](https://github.com/user-attachments/assets/0a9b0fce-3d26-4ff3-aa6b-98767e0fdd08)

**Comment by Dr-Noob** [comment]
You are running an old version of cpufetch. The last version is v1.05, please update and try again (you can find more information [here](https://github.com/Dr-Noob/cpufetch?tab=readme-ov-file#2-installation)).

**Comment by jesustejerina** [comment]
Nice, is correct.... I used make command... Thanks

![neofetch2](https://github.com/user-attachments/assets/497db0cd-4b94-4dde-bbb7-8ca48ada3469)

![cpufetch](https://github.com/user-attachments/assets/12fc0323-7a4f-4086-b16b-c517d83138a4)
