### ISSUE TITLE
Ampere Altra isn't properly detected

### ISSUE THREAD

**Issue by RossComputerGuy** [Dr-Noob/cpufetch#262]
No errors, just says Neoverse N1. SoC should say it's an Ampere Altra.
![image](https://github.com/user-attachments/assets/63bcc588-c77e-4ae3-a37b-5a44cef4d82d)

Adding `--debug` gives me this:
```
cpufetch v1.05 (Linux ARM build)
[Core 0] 0x413FD0C1 2200 MHz
[Core 1] 0x413FD0C1 2200 MHz
[Core 2] 0x413FD0C1 2200 MHz
[Core 3] 0x413FD0C1 2200 MHz
[Core 4] 0x413FD0C1 2200 MHz
[Core 5] 0x413FD0C1 2200 MHz
[Core 6] 0x413FD0C1 2200 MHz
[Core 7] 0x413FD0C1 2200 MHz
[Core 8] 0x413FD0C1 2200 MHz
[Core 9] 0x413FD0C1 2200 MHz
[Core 10] 0x413FD0C1 2200 MHz
[Core 11] 0x413FD0C1 2200 MHz
[Core 12] 0x413FD0C1 2200 MHz
[Core 13] 0x413FD0C1 2200 MHz
[Core 14] 0x413FD0C1 2200 MHz
[Core 15] 0x413FD0C1 2200 MHz
[Core 16] 0x413FD0C1 2200 MHz
[Core 17] 0x413FD0C1 2200 MHz
[Core 18] 0x413FD0C1 2200 MHz
[Core 19] 0x413FD0C1 2200 MHz
[Core 20] 0x413FD0C1 2200 MHz
[Core 21] 0x413FD0C1 2200 MHz
[Core 22] 0x413FD0C1 2200 MHz
[Core 23] 0x413FD0C1 2200 MHz
[Core 24] 0x413FD0C1 2200 MHz
[Core 25] 0x413FD0C1 2200 MHz
[Core 26] 0x413FD0C1 2200 MHz
[Core 27] 0x413FD0C1 2200 MHz
[Core 28] 0x413FD0C1 2200 MHz
[Core 29] 0x413FD0C1 2200 MHz
[Core 30] 0x413FD0C1 2200 MHz
[Core 31] 0x413FD0C1 2200 MHz
[Core 32] 0x413FD0C1 2200 MHz
[Core 33] 0x413FD0C1 2200 MHz
[Core 34] 0x413FD0C1 2200 MHz
[Core 35] 0x413FD0C1 2200 MHz
[Core 36] 0x413FD0C1 2200 MHz
[Core 37] 0x413FD0C1 2200 MHz
[Core 38] 0x413FD0C1 2200 MHz
[Core 39] 0x413FD0C1 2200 MHz
[Core 40] 0x413FD0C1 2200 MHz
[Core 41] 0x413FD0C1 2200 MHz
[Core 42] 0x413FD0C1 2200 MHz
[Core 43] 0x413FD0C1 2200 MHz
[Core 44] 0x413FD0C1 2200 MHz
[Core 45] 0x413FD0C1 2200 MHz
[Core 46] 0x413FD0C1 2200 MHz
[Core 47] 0x413FD0C1 2200 MHz
[Core 48] 0x413FD0C1 2200 MHz
[Core 49] 0x413FD0C1 2200 MHz
[Core 50] 0x413FD0C1 2200 MHz
[Core 51] 0x413FD0C1 2200 MHz
[Core 52] 0x413FD0C1 2200 MHz
[Core 53] 0x413FD0C1 2200 MHz
[Core 54] 0x413FD0C1 2200 MHz
[Core 55] 0x413FD0C1 2200 MHz
[Core 56] 0x413FD0C1 2200 MHz
[Core 57] 0x413FD0C1 2200 MHz
[Core 58] 0x413FD0C1 2200 MHz
[Core 59] 0x413FD0C1 2200 MHz
[Core 60] 0x413FD0C1 2200 MHz
[Core 61] 0x413FD0C1 2200 MHz
[Core 62] 0x413FD0C1 2200 MHz
[Core 63] 0x413FD0C1 2200 MHz
```

**Comment by Dr-Noob** [comment]
Nice machine! What is the output of `cpufetch --verbose`?

**Comment by RossComputerGuy** [comment]
```
[WARNING]: SoC detection failed using /proc/cpuinfo: No string found
[WARNING]: read_file: /sys/bus/nvmem/devices/rockchip-efuse0/nvmem: No such file or directory
[WARNING]: read_file: /sys/bus/nvmem/devices/rockchip-otp0/nvmem: No such file or directory
```

**Comment by Dr-Noob** [comment]
Another harsh SoC...Could you provide the output of `cat /proc/device-tree/compatible`? Seems like this will the be the only way to get this working (similar to #261).

**Comment by RossComputerGuy** [comment]
Ampere Altra doesn't use device trees.

**Comment by RossComputerGuy** [comment]
I just discovered the way to check is the PCIe bus, since the PCIe host bridge reports as "Ampere Computing" as the vendor. `/sys/bus/pci/devices/0000:00:00.0/vendor` will report `0x1def` which looking up that vendor, it says "Ampere Computing".

**Comment by Dr-Noob** [comment]
> I just discovered the way to check is the PCIe bus, since the PCIe host bridge reports as "Ampere Computing" as the vendor. `/sys/bus/pci/devices/0000:00:00.0/vendor` will report `0x1def` which looking up that vendor, it says "Ampere Computing".

Nice! What about `/sys/bus/pci/devices/0000:00:00.0/device`? It should report some value similar to [these](https://admin.pci-ids.ucw.cz/read/PC/1def).

**Comment by RossComputerGuy** [comment]
That says `0xe100`

**Comment by Dr-Noob** [comment]
Okay, so I have created a new branch `i262` with a patch. Can you give it a go?

**Comment by RossComputerGuy** [comment]
`guess_soc_from_pci` didn't match.

**Comment by RossComputerGuy** [comment]
`pci_device_is_useful` looks to have filtered it out.

**Comment by RossComputerGuy** [comment]
```diff
diff --git a/src/common/pci.c b/src/common/pci.c
index f23bc5a..fd31f83 100644
--- a/src/common/pci.c
+++ b/src/common/pci.c
@@ -130,7 +130,7 @@ void populate_pci_devices(struct pci_devices * pci) {
 // vendor is NVIDIA (to be extended in the future).
 // Should we also restrict to VGA controllers only?
 bool pci_device_is_useful(struct pci_device* dev) {
-  return dev->vendor_id == PCI_VENDOR_NVIDIA;
+  return dev->vendor_id == PCI_VENDOR_NVIDIA || dev->vendor_id == PCI_VENDOR_AMPERE;
 }

 // Filter the input list in order to get only those PCI devices which
```

**Comment by RossComputerGuy** [comment]
![image](https://github.com/user-attachments/assets/c4064956-ec72-4124-9701-b60dbaf09a88)

**Comment by bcran** [comment]
Thanks @RossComputerGuy - your patch makes the Ampere Altra identification work for me too!

**Comment by Dr-Noob** [comment]
Thanks for the feedback @RossComputerGuy @bcran. I have fixed the issue and improved the Ampere logo. If you guys could confirm it works as expected it would be great. Also, any feedback is welcomed. I'll merge into master whenever we are happy with it.

**Comment by bcran** [comment]
Yup that works. Thanks!

**Comment by RossComputerGuy** [comment]
Same for me

**Comment by Dr-Noob** [comment]
Merged, thank you both for the report and the feedback :+1:

**Comment by nullr0ute** [comment]
> +  return dev->vendor_id == PCI_VENDOR_NVIDIA || dev->vendor_id == PCI_VENDOR_AMPERE;

Might make sense to use hwdata? Of 8 systems I've tested it doesn't detect 5 of them properly. In one case doesn't even detect the Arm Cortex core.

**Comment by Dr-Noob** [comment]
> > * return dev->vendor_id == PCI_VENDOR_NVIDIA || dev->vendor_id == PCI_VENDOR_AMPERE;
> 
> Might make sense to use hwdata? Of 8 systems I've tested it doesn't detect 5 of them properly. In one case doesn't even detect the Arm Cortex core.

Could you open an issue with the output of `cpufetch --verbose`? Specially interesting to me is the case where it doesn't detect the cortex core. That way we can track and fix the issue.
