### ISSUE TITLE
Asahi Linux M1 Pro not properly detected

### ISSUE THREAD

**Issue by RossComputerGuy** [Dr-Noob/cpufetch#263]
![image](https://github.com/user-attachments/assets/bbf178d2-9e82-4227-be1e-e526aa0b3215)

Verbose:
```
[ERROR]: Unknown microarchitecture detected: IM=0x61 P=0x24 V=0x2 R=0x0
[VERSION]: cpufetch v1.05-38-gf631 (Linux ARM build)
Please, create a new issue with this error message, your smartphone/computer model, the output of 'cpufetch --verbose' and 'cpufetch --debug' on https://github.com/Dr-Noob/cpufetch/issues
[ERROR]: Unknown microarchitecture detected: IM=0x61 P=0x25 V=0x2 R=0x0
[VERSION]: cpufetch v1.05-38-gf631 (Linux ARM build)
Please, create a new issue with this error message, your smartphone/computer model, the output of 'cpufetch --verbose' and 'cpufetch --debug' on https://github.com/Dr-Noob/cpufetch/issues
[WARNING]: SoC detection failed using /proc/cpuinfo: No string found
[WARNING]: read_file: /sys/bus/nvmem/devices/rockchip-efuse0/nvmem: No such file or directory
[WARNING]: read_file: /sys/bus/nvmem/devices/rockchip-otp0/nvmem: No such file or directory
[WARNING]: guess_soc_from_uarch: No uarch matched the list
[WARNING]: guess_soc_from_pci: No PCI device matched the list
```

Debug:
```
[ERROR]: Unknown microarchitecture detected: IM=0x61 P=0x24 V=0x2 R=0x0
[VERSION]: cpufetch v1.05-38-gf631 (Linux ARM build)
Please, create a new issue with this error message, your smartphone/computer model, the output of 'cpufetch --verbose' and 'cpufetch --debug' on https://github.com/Dr-Noob/cpufetch/issues
[ERROR]: Unknown microarchitecture detected: IM=0x61 P=0x25 V=0x2 R=0x0
[VERSION]: cpufetch v1.05-38-gf631 (Linux ARM build)
Please, create a new issue with this error message, your smartphone/computer model, the output of 'cpufetch --verbose' and 'cpufetch --debug' on https://github.com/Dr-Noob/cpufetch/issues
cpufetch v1.05-38-gf631 (Linux ARM build)
[Core 0] 0x612F0240 2064 MHz
[Core 1] 0x612F0240 2064 MHz
[Core 2] 0x612F0250 3228 MHz
[Core 3] 0x612F0250 3228 MHz
[Core 4] 0x612F0250 3228 MHz
[Core 5] 0x612F0250 3228 MHz
[Core 6] 0x612F0250 3228 MHz
[Core 7] 0x612F0250 3228 MHz
[Core 8] 0x612F0250 3228 MHz
[Core 9] 0x612F0250 3228 MHz
```

**Comment by Dr-Noob** [comment]
(This is a pretty complicated scenario, but we can try to make this work). Can you provide the output of `cat /proc/device-tree/compatible` and see if there is any PCI device that could help here to infer the SoC? I'll take care of the microarchitecture issue.

**Comment by RossComputerGuy** [comment]
That file has: `apple,j314sapple,t6000apple,arm-platform`

**Comment by CarterLi** [comment]
t6000 is the code name of Apple Silicon SOC. You can find the detail here: https://github.com/AsahiLinux/docs/wiki/Codenames

[Fastfetch](https://github.com/fastfetch-cli/fastfetch/blob/dev/src/detection/cpu/cpu.c#L22-L41) uses:

```c
switch (code)
{
    case 8103: return "Apple M1";
    case 6000: return "Apple M1 Pro";
    case 6001: return "Apple M1 Max";
    case 6002: return "Apple M1 Ultra";
    case 8112: return "Apple M2";
    case 6020: return "Apple M2 Pro";
    case 6021: return "Apple M2 Max";
    case 6022: return "Apple M2 Ultra";
    case 8122: return "Apple M3";
    case 6030: return "Apple M3 Pro";
    case 6031:
    case 6034: return "Apple M3 Max";
    default: return "Apple Silicon";
}
```

**Comment by Dr-Noob** [comment]
I've pushed a (bit crappy) fix in branch `i263`. Could you check if that works for you? Thanks for the feedback :+1:

**Comment by RossComputerGuy** [comment]
It segfaults :crying_cat_face:

**Comment by RossComputerGuy** [comment]
`get_soc` seems to be borked.

**Comment by RossComputerGuy** [comment]
Seems `read_file` might've borked it:
```
Run till exit from #0  read_file (path=0x41ac10 "/proc/device-tree/compatible", len=0xffffffffc1bc) at src/common/udev.c:50
0x0000000000404588 in get_devtree_compatible () at src/common/udev.c:360
360	  if ((buf = read_file(_PATH_DEVTREE, &filelen)) == NULL) {
Value returned is $4 = 0x4574b0 "apple,j314s"
```

**Comment by Dr-Noob** [comment]
My bad! I have pushed a fix, what about now?

**Comment by RossComputerGuy** [comment]
Yeah, that works.
![image](https://github.com/user-attachments/assets/f3a752e7-b263-48f2-b4e2-71f6525ae74c)

**Comment by RossComputerGuy** [comment]
```
Breakpoint 1, guess_soc_from_devtree (soc=0x455060) at src/arm/soc.c:917
917	struct system_on_chip* guess_soc_from_devtree(struct system_on_chip* soc) {
(gdb) step
918	  char* dt = get_devtree_compatible();
(gdb)
get_devtree_compatible () at src/common/udev.c:356
356	char* get_devtree_compatible(void) {
(gdb)
360	  if ((buf = read_file(_PATH_DEVTREE, &filelen)) == NULL) {
(gdb)
read_file (path=0x41ac18 "/proc/device-tree/compatible", len=0xffffffffc1bc) at src/common/udev.c:50
50	char* read_file(char* path, int* len) {
(gdb) finish
Run till exit from #0  read_file (path=0x41ac18 "/proc/device-tree/compatible", len=0xffffffffc1bc) at src/common/udev.c:50
0x0000000000404588 in get_devtree_compatible () at src/common/udev.c:360
360	  if ((buf = read_file(_PATH_DEVTREE, &filelen)) == NULL) {
Value returned is $1 = 0x4574b0 "apple,j314s"
(gdb) step
364	  return buf;
```
Seems `read_file` still isn't pulling the entire string.

**Comment by Dr-Noob** [comment]
Yeah, I was not careful with the NULL characters in the file. New patch, can you try again?

**Comment by RossComputerGuy** [comment]
Sweet, that works now.
![image](https://github.com/user-attachments/assets/d42fa6c2-ffa5-4954-976c-568f5cd403cc)

**Comment by Dr-Noob** [comment]
> t6000 is the code name of Apple Silicon SOC. You can find the detail here: https://github.com/AsahiLinux/docs/wiki/Codenames
> 
> [Fastfetch](https://github.com/fastfetch-cli/fastfetch/blob/dev/src/detection/cpu/cpu.c#L22-L41) uses:
> 
> ```c
> switch (code)
> {
>     case 8103: return "Apple M1";
>     case 6000: return "Apple M1 Pro";
>     case 6001: return "Apple M1 Max";
>     case 6002: return "Apple M1 Ultra";
>     case 8112: return "Apple M2";
>     case 6020: return "Apple M2 Pro";
>     case 6021: return "Apple M2 Max";
>     case 6022: return "Apple M2 Ultra";
>     case 8122: return "Apple M3";
>     case 6030: return "Apple M3 Pro";
>     case 6031:
>     case 6034: return "Apple M3 Max";
>     default: return "Apple Silicon";
> }
> ```

Thanks, this is very useful. I have incorporated a similar (but less efficient) approach. Fastfetch is indeed a nice project! :ok_hand:

**Comment by Dr-Noob** [comment]
> Sweet, that works now. ![image](https://private-user-images.githubusercontent.com/19699320/360594322-d42fa6c2-ffa5-4954-976c-568f5cd403cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzOTkyNjMsIm5iZiI6MTcyNDM5ODk2MywicGF0aCI6Ii8xOTY5OTMyMC8zNjA1OTQzMjItZDQyZmE2YzItZmZhNS00OTU0LTk3NmMtNTY4ZjVjZDQwM2NjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDA3NDI0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3Mjc1ZjlmNGM4MmQwZGY2YzdjYzA3ZWU3MDIyZjA0YzQxYzdjY2ZmYzE4N2QyNWZkYTVlOTdkMjVkYjQzYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9VTJSEbvrkkDa4-q_Rk3aeZSAvuwpPe6vmVPm5eJ8aA)

Awesome! I have merged this into master now. Thank you for your feedback and feel free to report more issues if you find any unsupported device around. It helps a lot :+1:
