### ISSUE TITLE
proxmox not recognized

### ISSUE THREAD

**Issue by jko-tab** [Dr-Noob/cpufetch#267]
Hi, I run cpufetch under Zorin OS v17 Core which runs as VM in proxmox 8.2.2. When I run cpufetch and cpufetch --debug, I get the message in the attached screenshot. 
![Screenshot from 2024-08-21 19-00-12](https://github.com/user-attachments/assets/daaf050c-5769-47a7-a6a2-47baf6df5eb0)

**Comment by Dr-Noob** [comment]
You are running an old version of cpufetch. The last version is v1.06, please update and try again (you can find more information [here](https://github.com/Dr-Noob/cpufetch?tab=readme-ov-file#2-installation)). Also, what CPU do you have? From the CPUID dump it seems to be an AMD but somehow the VM is reporting that your CPU is Intel.

**Comment by jko-tab** [comment]
I installed cpufetch 1.06 directly from github, but still have the problem: jkomarek@Zorin-v17-VM:~/cpufetch$ cpufetch
[ERROR]: Unknown microarchitecture detected: M=0xB EM=0x6 F=0xF EF=0x0 S=0x1
[VERSION]: cpufetch v1.06-4-g321a (Linux x86 / x86_64 build)
Please, create a new issue with this error message, the output of 'cpufetch' and 'cpufetch --debug' on https://github.com/Dr-Noob/cpufetch/issues
perf_event_open: Permission denied
[ERROR]: You may not have permission to collect stats.
Consider tweaking /proc/sys/kernel/perf_event_paranoid or running as root
[VERSION]: cpufetch v1.06-4-g321a (Linux x86 / x86_64 build)

                                                              
                                                              
                                                              Name:                QEMU Virtual CPU version 2.5+
                                                              Hypervisor:          KVM
                                                              Microarchitecture:   Unknown
                                                              Technology:          Unknown
                                                              Max Frequency:       Unknown
                                                              Sockets:             4
                                                              Cores:               4 cores
                                                              Cores (Total):       16 cores
                                                              SSE:                 SSE,SSE2,SSE3,SSSE3,SSE4.1,SSE4.2
                                                              L1i Size:            32KB (512KB Total)
                                                              L1d Size:            32KB (512KB Total)
                                                              L2 Size:             4MB (64MB Total)
                                                              L3 Size:             16MB (64MB Total)
                                                              Peak Performance:    Unknown
                                                              
                                                              
                                                              

jkomarek@Zorin-v17-VM:~/cpufetch$ cpufetch --version
cpufetch v1.06-4-g321a (Linux x86 / x86_64 build)
jkomarek@Zorin-v17-VM:~/cpufetch$ cpufetch --debug
[ERROR]: Unknown microarchitecture detected: M=0xB EM=0x6 F=0xF EF=0x0 S=0x1
[VERSION]: cpufetch v1.06-4-g321a (Linux x86 / x86_64 build)
Please, create a new issue with this error message, the output of 'cpufetch' and 'cpufetch --debug' on https://github.com/Dr-Noob/cpufetch/issues
perf_event_open: Permission denied
[ERROR]: You may not have permission to collect stats.
Consider tweaking /proc/sys/kernel/perf_event_paranoid or running as root
[VERSION]: cpufetch v1.06-4-g321a (Linux x86 / x86_64 build)
cpufetch v1.06-4-g321a (Linux x86 / x86_64 build)
QEMU Virtual CPU version 2.5+
- Hypervisor: KVM
- Max standard level: 0x0000000D
- Max extended level: 0x8000000A
- Hybrid Flag: 0
- CPUID dump: 0x00060FB1
jkomarek@Zorin-v17-VM:~/cpufetch$ 

The CPU of my little proxmox server is an Intel Core i5 13500t. Not sure why proxmox reports an AMD to the VM.

**Comment by jko-tab** [comment]
In addition, I ran it as super user: jkomarek@Zorin-v17-VM:~/cpufetch$ sudo cpufetch --debug
[ERROR]: Unknown microarchitecture detected: M=0xB EM=0x6 F=0xF EF=0x0 S=0x1
[VERSION]: cpufetch v1.06-4-g321a (Linux x86 / x86_64 build)
Please, create a new issue with this error message, the output of 'cpufetch' and 'cpufetch --debug' on https://github.com/Dr-Noob/cpufetch/issues
perf_event_open: No such file or directory
cpufetch v1.06-4-g321a (Linux x86 / x86_64 build)
QEMU Virtual CPU version 2.5+
- Hypervisor: KVM
- Max standard level: 0x0000000D
- Max extended level: 0x8000000A
- Hybrid Flag: 0
- CPUID dump: 0x00060FB1
jkomarek@Zorin-v17-VM:~/cpufetch$

**Comment by Dr-Noob** [comment]
I'm afraid I cannot do much here. If your CPU is a 13500t and the reported CPUID dump is `00060FB1` then it's a clear indication that the VM is tampering the values for the CPU, and a detection tool like cpufetch can do nothing about it. You'll find similar issues with other tools. If you want proper detection you will need to avoid the virtual machine.
