### ISSUE TITLE
Makefile installs plain text man page with `.gz` file-extension

### ISSUE THREAD

**Issue by carlsmedstad** [Dr-Noob/cpufetch#269]
Hey :wave: Arch Linux maintainer here

The `install` Make-target installs the plaintext man page `cpufetch.1` as `cpufetch.1.gz` ([here](https://github.com/Dr-Noob/cpufetch/blob/master/Makefile#L123)), i.e. with the incorrect file extension `.gz`. Please change this to either:

* Install the plaintext man page as `cpufetch.1`:
  ```sh
  install -Dm644 "cpufetch.1" "$(DESTDIR)$(PREFIX)/share/man/man1/cpufetch.1"
  ```
* Gzip the man page and install it as `cpufetch.1.gz`:
  ```sh
  gzip cpufetch.1
  install -Dm644 "cpufetch.1.gz" "$(DESTDIR)$(PREFIX)/share/man/man1/cpufetch.1.gz"
  ```

Arch Linux issue: https://gitlab.archlinux.org/archlinux/packaging/packages/cpufetch/-/issues/1

Much appreciated, thank you!

**Comment by Dr-Noob** [comment]
Oops, my bad! I have pushed a fix following the first approach. Thank you for reporting :+1:
