### ISSUE TITLE
ThinkPad X13s

### ISSUE THREAD

**Issue by abenson** [Dr-Noob/cpufetch#272]
[debug.txt](https://github.com/user-attachments/files/16824973/debug.txt)
[verbose.txt](https://github.com/user-attachments/files/16824974/verbose.txt)

Let me know if you need anything else!

**Comment by Wunkolo** [comment]
https://github.com/Dr-Noob/cpufetch/issues/226 also captures a more general interest for Windows on Arm.

**Comment by Dr-Noob** [comment]
> #226 also captures a more general interest for Windows on Arm.
> 
> Curious if a PR of this feature would be approved.

Indeed, a PR of this feature would be review and approved with great pleasure! The only requirement I would ask for is good documentation to support the implementation. For now I'll add support for ThinkPad X13s myself for Linux. Working on it...

**Comment by Dr-Noob** [comment]
> [debug.txt](https://github.com/user-attachments/files/16824973/debug.txt) [verbose.txt](https://github.com/user-attachments/files/16824974/verbose.txt)
> 
> Let me know if you need anything else!

Latest patches give support for the microarchitecture. I'd need the output of `hexdump -C /proc/device-tree/compatible` to also give support for the SoC.

**Comment by abenson** [comment]
[debug.txt](https://github.com/user-attachments/files/16838934/debug.txt)
[device-tree.txt](https://github.com/user-attachments/files/16838935/device-tree.txt)
[verbose.txt](https://github.com/user-attachments/files/16838936/verbose.txt)

**Comment by Dr-Noob** [comment]
Looks good! Branch `i273` should make the SoC detection work.

**Comment by ausil** [comment]
I can confirm that  on branch i273 detection works correctly on linux

**Comment by Dr-Noob** [comment]
Thanks for the confirmation! Merged into master now.
