### ISSUE TITLE
Display more features on AArch64

### ISSUE THREAD

**Issue by hrw** [Dr-Noob/cpufetch#282]
cpufetch on AArch64 shows "Features:          NEON,SHA1,SHA2,AES,CRC32" which is kind of worthless.

Neon support is present in all cores, SHA1/2/AES/CRC32 are v8.0 crypto part which is present in nearly every cpu.

Compare it with 'Features' flag of /proc/cpuinfo:
```
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma lrcpc dcpop sha3 asimddp sha512 asimdfhm dit uscat ilrcpc flagm ssbs sb paca pacg dcpodp flagm2 frint
```

Atomics/uscat, paca/pacg, sve/sve2/sme, bti, rng are interesting cpu features to show.

**Comment by Dr-Noob** [comment]
Duplicated of #132 (it's been a long time since I planned to improve this)
