### ISSUE TITLE
Add support for Zicbop found on SpacemiT K1/M1 CPU

### ISSUE THREAD

**Issue by cwt** [Dr-Noob/cpufetch#285]
Currently there will be an error:
```
[ERROR]: parse_multi_letter_extension: Unknown multi-letter extension: zicbop
```

FYI: https://github.com/riscv/riscv-CMOs/blob/master/cmobase/Zicbop.adoc

**Comment by Dr-Noob** [comment]
Thanks for the report. I prefer to keep small patches like this as issues rather than PR. Can you confirm the latest patch works as expected? A picture would also be greatly appreciated, thanks!

**Comment by cwt** [comment]
@Dr-Noob yes, it works.
![Screenshot from 2024-09-11 15-47-27](https://github.com/user-attachments/assets/a0019bbf-f752-4126-96a9-b8f6d3cdff72)

**Comment by Dr-Noob** [comment]
Nice. If you post the output of `cpufetch --verbose` in a new issue we can try fixing the unkown SoC and microarchitecture :+1:
