### ISSUE TITLE
AMD Phenom II 955 Issue

### ISSUE THREAD

**Issue by linuxergr** [Dr-Noob/cpufetch#33]
Hi,

Thanks for making this nice fetching tool.

When cpufetch (Release 0.7) is executed, I get the error: 

`[ERROR]: Can't read cache information from cpuid (needed extended level is -2147483619, max is -2147483621)`

 ![Screenshot](https://i.imgur.com/m5wuIsS.png)

**Comment by Dr-Noob** [comment]
Hi @linuxergr, thanks for your feedback.

Interesting to see an AMD processor old enough that it does not support fetching cache information from CPUID. 

Before proceeding, I would need a bit more information. Would you mind sharing the output of `lscpu -C`? If your lscpu version is too old it will not include the `-C` option, in which case you could run `lscpu | grep -i cache`. The output of `cat /sys/devices/system/cpu/cpu0/cache/index0/size` would be very useful too.

**Comment by linuxergr** [comment]
Ηι @Dr-Noob 

My output of both commands is as below (lscpu -C works):

![Screenshot](https://i.imgur.com/cIcPyGz.png)

Note that cpufetch was working at the past

Regards

**Comment by linuxergr** [comment]
And this is my cpuid output

[https://paste.artixlinux.org/view/57c43883](https://paste.artixlinux.org/view/57c43883)

**Comment by Dr-Noob** [comment]
I just pushed a commit in a new branch called bugfix to fix the issue. Please, try it out and confirm if you get the same output as `lscpu -C`. Feel free to close the issue in such case.

**Comment by linuxergr** [comment]
Hi @Dr-Noob 

I confirm that the output is ok

![Screenshot](https://i.imgur.com/7Dh4M1u.png)

Regards
