### ISSUE TITLE
[ARM] Cache sizes

### ISSUE THREAD

**Issue by Wunkolo** [Dr-Noob/cpufetch#35]
There seems to be no user-level way to get these variables and most kernels just return "0"for all the `LEVELn` system configuration variables:
```
% getconf -a | grep CACHE
LEVEL1_ICACHE_SIZE                 0
LEVEL1_ICACHE_ASSOC                0
LEVEL1_ICACHE_LINESIZE             64
LEVEL1_DCACHE_SIZE                 0
LEVEL1_DCACHE_ASSOC                0
LEVEL1_DCACHE_LINESIZE             64
...
```

I've been doing some research and it looks like your best bet is to use the uarch of the chip itself and approximate/best-guess by using a static LUT of known values for each uarch, much like pytorch does by using the technical reference manuals:

https://github.com/pytorch/cpuinfo/blob/ed8b86a253800bafdb7b25c5c399f91bff9cb1f3/src/arm/cache.c#L950-L965

**Comment by Dr-Noob** [comment]
Yes, I am aware of the situation. 

For the ARM part of cpufetch I am trying to work on a given area at a time, and right now I'm working on the SoC detection. 

In the future, I will work on cache detection, but I planned to follow a similar approach as cpuinfo. As you said, the idea is to use a LUT for each microarchitecture. It is a quite painful process. But if I'm not mistaken, there is no other way to do this without running a kernel module...

If you find a better approach in the meanwhile, let me know.

Thank you for your help!
