### ISSUE TITLE
[ERROR]: Found unified cache at level 4 (expected == 2 or 3)

### ISSUE THREAD

**Issue by Skaytacium** [Dr-Noob/cpufetch#43]
`cpufetch --debug` gives the same error, nothing new.

![image](https://user-images.githubusercontent.com/58383260/113521943-843d5600-95ba-11eb-803b-d7bb1688340b.png)

**Comment by Dr-Noob** [comment]
Hi,

I've just pushed a commit to master branch. Please, try it and paste the output here. If it works well now, you can close the issue afterwards.

Thanks!

**Comment by Dr-Noob** [comment]
Closing the issue because it didn't receive any messages after a long time.

**Comment by Skaytacium** [comment]
Oh, I'm really sorry I haven't checked my GitHub for a while, and I completely forgot about me opening up this issue.

![image](https://user-images.githubusercontent.com/58383260/116505344-43461200-a8d8-11eb-95b6-c072da769d4b.png)

This is what it says, I shifted shells from fish to zsh, I'm not sure if that matters.

![image](https://user-images.githubusercontent.com/58383260/116505373-59ec6900-a8d8-11eb-837a-4054ff4e0a2e.png)

This is what normal sh returns.

**Comment by Dr-Noob** [comment]
That segmentation fault looks pretty bad...

If you have time, I would appreciate if you could provide additional information about what is going on, so we can fix the issue. [This small guide](https://github.com/Dr-Noob/cpufetch/blob/master/CONTRIBUTING.md#creating-an-issue) explains in a nutshell what to do and what information to provide in these cases.

Reopening the issue. Thanks!

**Comment by Skaytacium** [comment]
Interesting, I have posted a Pastebin link and an image is attached.

https://pastebin.com/GPyqLYUk

![image](https://user-images.githubusercontent.com/58383260/116579577-250c0080-a930-11eb-8644-1917c310346e.png)

Thanks a lot for the reopen, sorry again for my forgetful nature.

**Comment by Dr-Noob** [comment]
Ummmm... unfortunately, that's not enough information so I can track the problem.

Two things:
- Can you scpecify which is your CPU model? (information given by cpufetch run with valgrind is invalid). 
- Follow [the gdb part of the guide](https://github.com/Dr-Noob/cpufetch/blob/master/CONTRIBUTING.md#option-2-use-this-option-if-you-cant-work-with-option-1) (`Option 2`) and attach the output of it too (pastebin is enough), because valgrind does not output any error.

Thanks!

**Comment by Skaytacium** [comment]
Oh yeah sure,

The CPU is an [Intel i7 4870HQ](https://ark.intel.com/content/www/us/en/ark/products/83504/intel-core-i7-4870hq-processor-6m-cache-up-to-3-70-ghz.html) and a Macbook 11, 5 (If that matters)

Pastebin: https://pastebin.com/UEQruCMR

Thanks for following up so quickly.

**Comment by Dr-Noob** [comment]
Damn... that was my bad.

I have uploaded a possible fix for this issue in the `bugfix` branch. Give it a try (remember to move to the branch: `git checkout bugfix`) and let me know if it works or not. I also added a message to help us understand what is going on in case that the fix I have pushed does not work. But let's hope it does work!

**Comment by Skaytacium** [comment]
Hey, that works perfectly as far as I can see. I have attached Pastebin output, any idea on when this will be merged with master?

https://pastebin.com/ucEmMs98

**Comment by Dr-Noob** [comment]
That's great! I've merged this change to master. 

Don't worry about the warnings with the verbose parameter. When `--verbose` is specified, cpufetch prints all the warnings, so they are not shown if you run cpufetch with no options. In your case, warnings are harmless.

Thanks for your feedback!

**Comment by Skaytacium** [comment]
Ah okay, thanks a lot for the blazing fast response, always great to see someone passionate and supportive about the project they made.
