### ISSUE TITLE
Invalid L1i size: 96KB

### ISSUE THREAD

**Issue by alpvonkri** [Dr-Noob/cpufetch#45]
Git version: 4900c10
openSUSE Leap 15.2
Kernel 5.3.18
AMD A10-8700P Radeon R6, 10 Compute Cores 4C+6G

cpufetch --debug
[ERROR]: Invalid L1i size: 96KB
Please, create a new issue with this error message and the output of 'cpufetch --debug' in https://github.com/Dr-Noob/cpufetch/issues

**Comment by Dr-Noob** [comment]
Hi,

Thanks for posting the issue, but we already have this issue tracked on issue #39. 

I'm closing this issue, please refer to that issue to track the problem. You can temporary fix the issue by moving to the `bugfix` branch. Please, move to this branch (`git checkout bugfix`) and post the output of `cpufetch --debug` on issue #39.

Thanks!
