### ISSUE TITLE
[ERROR]: Invalid L2 size: 4MB

### ISSUE THREAD

**Issue by ahosam** [Dr-Noob/cpufetch#46]
$./cpufetch
[ERROR]: Invalid L2 size: 4MB
Please, create a new issue with this error message and the output of 'cpufetch --debug' in https://github.com/Dr-Noob/cpufetch/issues
Segmentation fault (core dumped)

**Comment by ahosam** [comment]
on Apple MAC working fine, on ubuntu-18.04 got this error,

**Comment by Dr-Noob** [comment]
Hi,

Please, specify the CPU model where you get the error. You can find it using the `lscpu` command.

Thanks!

**Comment by ahosam** [comment]
`PU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              8
On-line CPU(s) list: 0-7
Thread(s) per core:  1
Core(s) per socket:  1
Socket(s):           8
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               60
Model name:          Intel Core Processor (Haswell, no TSX)
Stepping:            1
CPU MHz:             2693.670
BogoMIPS:            5387.34
Virtualization:      VT-x
Hypervisor vendor:   KVM
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            4096K
L3 cache:            16384K
NUMA node0 CPU(s):   0-7
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 syscall nx rdtscp lm constant_tsc rep_good nopl xtopology cpuid tsc_known_freq pni pclmulqdq vmx ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm cpuid_fault invpcid_single pti tpr_shadow vnmi flexpriority ept vpid fsgsbase bmi1 avx2 smep bmi2 erms invpcid xsaveopt arat`

**Comment by Dr-Noob** [comment]
Interesting. 

I've just pushed a new commit. Please, update the project and paste here the output of `cpufetch` and `cpufetch --debug`.

Thanks!

**Comment by ahosam** [comment]
working fine, 
Thanks
