### ISSUE TITLE
Wrong number of physical cores on AMD(Ryzen)

### ISSUE THREAD

**Issue by Dr-Noob** [Dr-Noob/cpufetch#5]

**Comment by alichtman** [comment]
My Ryzen 3700X is detected properly.

```
                                                              Name:       AMD Ryzen 7 3700X 8-Core Processor
                                                              Frequency:  3.60GHz
     @@@@      @@@       @@@   @@@@@@@@        ############   N.Cores:    8 cores(16 threads)
    @@@@@@     @@@@@    @@@@   @@@    @@@@       ##########   AVX:        AVX,AVX2
   @@@  @@@    @@@@@@@@@@@@@   @@@      @@      #      ####   SSE:        SSE,SSE2,SSE3,SSSE3,SSE4_1,SSE4_2
  @@@    @@@   @@@  @@@  @@@   @@@      @@@   ###      ####   FMA:        FMA3
 @@@@@@@@@@@@  @@@       @@@   @@@     @@@   ####    ## ###   AES:        Yes
 @@@      @@@  @@@       @@@   @@@@@@@@@     ########    ##   SHA:        Yes
                                                              L1 Size:    32KB(Data)32KB(Instructions)
                                                              L2 Size:    512KB
                                                              L3 Size:    16384K
                                                              Peak FLOPS: 921.60 GFLOP/s

```

**Comment by Dr-Noob** [comment]
Thank you for your AMD Ryzen output.

Unfortunately, I have very few AMD Ryzen available to test cpufetch on, so this is very useful. Since I opened this issue so long time ago, I don't know if the issue actually exists or it was just a confusion. At least, from what I see in your output, the Peak FLOPS is wrong, so this is also a thing to check (if I'm not wrong, it should be the half).

I will have a look at this when I have free time.

**Comment by Dr-Noob** [comment]
I hope this is fixed thanks to commit 1ce6b97

**Comment by alichtman** [comment]
![image](https://user-images.githubusercontent.com/20600565/85355498-5aef8580-b4d2-11ea-88c3-5b86e8ce4d5c.png)

Here's what I have now

**Comment by Dr-Noob** [comment]
Thank you again for sharing your output!

Yes, the output seems to be totally correct.

**Comment by alichtman** [comment]
No problem.
