### ISSUE TITLE
[ERROR]: Could not open '/sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq'

### ISSUE THREAD

**Issue by fabrizio-cantalupo** [Dr-Noob/cpufetch#50]
doing cpufetch --debug it shown this:

open: No such file or directory
[ERROR]: Could not open '/sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq'
Please, create a new issue with this error message and the output of 'cpufetch --debug' in https://github.com/Dr-Noob/cpufetch/issues
cpufetch v0.96 (x86_64 build)
AMD Ryzen 3 3200G with Radeon Vega Graphics 
- Max standard level: 0x0000000D
- Max extended level: 0x8000001F
- CPUID dump: 0x00810F81

**Comment by Dr-Noob** [comment]
Hi, thanks for posting the issue.

I assume that you are running this under Linux and you are not using a virtual machine. Is that true? If it is, please paste the output of `lscpu` command.

Thanks!

**Comment by fabrizio-cantalupo** [comment]
> Hi, thanks for posting the issue.
> 
> I assume that you are running this under Linux and you are not using a virtual machine. Is that true? If it is, please paste the output of `lscpu` command.
> 
> Thanks!

Yes! I'm using a 3200g in Arch. Is not a virtual machine, here is the output:

[fabrizio@3200g ~]$ lscpu
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   43 bits physical, 48 bits virtual
CPU(s):                          4
On-line CPU(s) list:             0-3
Thread(s) per core:              1
Core(s) per socket:              4
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       AuthenticAMD
CPU family:                      23
Model:                           24
Model name:                      AMD Ryzen 3 3200G with Radeon Vega Graphics
Stepping:                        1
CPU MHz:                         3600.099
BogoMIPS:                        7203.20
Virtualization:                  AMD-V
L1d cache:                       128 KiB
L1i cache:                       256 KiB
L2 cache:                        2 MiB
L3 cache:                        4 MiB
NUMA node0 CPU(s):               0-3
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disable
                                 d via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __u
                                 ser pointer sanitization
Vulnerability Spectre v2:        Mitigation; Full AMD retpoline, IBPB conditi
                                 onal, STIBP disabled, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep 
                                 mtrr pge mca cmov pat pse36 clflush mmx fxsr
                                  sse sse2 ht syscall nx mmxext fxsr_opt pdpe
                                 1gb rdtscp lm constant_tsc rep_good nopl non
                                 stop_tsc cpuid extd_apicid aperfmperf pni pc
                                 lmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2
                                  movbe popcnt aes xsave avx f16c rdrand lahf
                                 _lm cmp_legacy svm extapic cr8_legacy abm ss
                                 e4a misalignsse 3dnowprefetch osvw skinit wd
                                 t tce topoext perfctr_core perfctr_nb bpext 
                                 perfctr_llc mwaitx cpb hw_pstate sme ssbd se
                                 v ibpb vmmcall sev_es fsgsbase bmi1 avx2 sme
                                 p bmi2 rdseed adx smap clflushopt sha_ni xsa
                                 veopt xsavec xgetbv1 xsaves clzero irperf xs
                                 aveerptr arat npt lbrv svm_lock nrip_save ts
                                 c_scale vmcb_clean flushbyasid decodeassists
                                  pausefilter pfthreshold avic v_vmsave_vmloa
                                 d vgif overflow_recov succor smca

**Comment by Dr-Noob** [comment]
Interesting...🤔

This is gonna be fun. Can you paste the output of `strace lscpu 2>&1 | grep -i 'freq'`?

**Comment by fabrizio-cantalupo** [comment]
it doesen't give any output. Btw, updating lscpu the bug has disappeared

**Comment by Dr-Noob** [comment]
You mean that you updated lscpu and now `cpufetch` do not throw any error, right? Does `cpufetch` print the frequency (which sould be 3.6 GHz)?
