### ISSUE TITLE
Add microarchitecture level detection and display

### ISSUE THREAD

**Issue by dylanmtaylor** [Dr-Noob/cpufetch#56]
Please add a feature to detect and display the microarchitecture level (x86-64 v2, etc.)

This might be helpful if you decide to implement this: https://unix.stackexchange.com/questions/631217/how-do-i-check-if-my-cpu-supports-x86-64-v2

**Comment by Dr-Noob** [comment]
Hi,

Thank you for your suggestion, I didn't know about that. I don't like it, so I'm not going to add that feature. Maybe in the future if this concept of "x86-64 micro-architecture levels" gets more popularity I will reconsider it.

Closing
