### ISSUE TITLE
[ERROR]: Invalid L2 size: 4MB

### ISSUE THREAD

**Issue by KvizadSaderah** [Dr-Noob/cpufetch#60]
[ERROR]: Invalid L2 size: 4MB
Please, create a new issue with this error message and the output of 'cpufetch --debug' in https://github.com/Dr-Noob/cpufetch/issues
cpufetch v0.96 (x86_64 build)
Intel Core Processor (Haswell, no TSX)
- Hypervisor: KVM
- Max standard level: 0x0000000D
- Max extended level: 0x80000008
- CPUID dump: 0x000306C1

Name:              Intel Core Processor (Haswell, no TSX)
Hypervisor:        KVM
Microarchitecture: Haswell
Technology:        22nm
Max Frequency:     Unknown
Cores:             1 cores
AVX:               AVX,AVX2
FMA:               FMA3
L1i Size:          32KB
L1d Size:          32KB
L2 Size:           4MB
L3 Size:           16MB
Peak Performance:  Unknown

**Comment by Dr-Noob** [comment]
Hi, thanks for your issue. 

What's the real name of the CPU? It does not appear in your message, as it has been replaced by "Intel Core Processor (Haswell, no TSX)" by KVM.

**Comment by KvizadSaderah** [comment]
Hi!
I'm not sure about this, because it is a VPS. 
And support also doesn't provide clear info, they say to check dedicated servers info: and processor there like:
Intel Xeon E3-1230v6 - 4 c / 8 t - 3.5 GHz / 3.9 GHz 
Intel i7-7700K - 4 c / 8 t - 4.2 GHz / 4.5 GHz 
Intel Xeon E5-1650v4 - 6 c / 12 t - 3.6 GHz / 4 GHz 
Intel 2x Xeon E5-2630v3 - 16 c / 32 t - 2.4 GHz / 3.2 GHz

**Comment by Dr-Noob** [comment]
I've updated the project since your first message. Please give it a try again, and re-open the issue again if you still have any problems.

Closing.
