### ISSUE TITLE
Bigest CPU Ever: 42 Meters wide Technology?

### ISSUE THREAD

**Issue by derestle-htwg** [Dr-Noob/cpufetch#61]
Either Minecraft has to give up the inofficial title of the biggest transistors (1 Chunk in Minecraft is approx 1 Meter)
or the tool reads the Technology wrong

![grafik](https://user-images.githubusercontent.com/5612007/113990006-4e65cf00-9851-11eb-88e3-411d5635b837.png)

**Comment by Dr-Noob** [comment]
😂😂 That must been a heavy CPU!

Please checkout to `bugfix2` branch and try the latest commit. It should print "Unknown" in the technology.

About the L2 size, I gotta ask you. What is the exact model of your CPU?

Thanks!

**Comment by Dr-Noob** [comment]
Closing the issue because it hasn't received any notifications after two weeks.

The fix is in the master branch now. Feel free to reopen the issue if the problem still occurs.
