### ISSUE TITLE
Add support for Intel Rocket Lake CPUs

### ISSUE THREAD

**Issue by Elveman** [Dr-Noob/cpufetch#68]
When trying to run cpufetch --debug on my Core i5-11500, it throws the following error:
```
[ERROR]: Unknown microarchitecture detected: M=0x00000007 EM=0x0000000A F=0x00000006 EF=0x00000000 S=0x00000001
Please, create a new issue with this error message and the output of 'cpufetch --debug' in https://github.com/Dr-Noob/cpufetch/issues
cpufetch v0.96 (x86_64 build)
11th Gen Intel(R) Core(TM) i5-11500 @ 2.70GHz
- Max standard level: 0x0000001B
- Max extended level: 0x80000008
- CPUID dump: 0x000A0671
```

**Comment by Dr-Noob** [comment]
Hi, thanks for the report!

I just pushed a commit to `bugfix3` branch. Give it a try and let me know if now the dectection works properly. If it does, close the issue and I will merge the commit to master afterwards.

**Comment by Elveman** [comment]
Got it, I'll try as soon as I get home from work (in 6 hours or so)

**Comment by Elveman** [comment]
![Screenshot_20210409_205530](https://user-images.githubusercontent.com/15056829/114221580-2a4fde00-9976-11eb-87f0-9aca703709f0.png)
Well, now it works just fine, so I think this issue can be closed. Thanks :+1:
