### ISSUE TITLE
Shifting signed integers into overflows invokes undefined behavior

### ISSUE THREAD

**Issue by stephan-cr** [Dr-Noob/cpufetch#76]
Code like

```c
(int)1 << 31
```

invokes undefined behavior, since the result would overflow an `int`. Signed integer overflow is undefined behavior.

I would recommend to use unsigned integers, because they are designed for bit level operations. For the example above:

```c
1U << 31
```

The clang/gcc option `-fsanitize=undefined` is quite helpful to detect such issues.

**Comment by Dr-Noob** [comment]
Thanks for your suggestion. 

You are absolutely right. I will make a commit soon to fix this. However, I'm unable to get the `-fsanitize=undefined` working. For me it does not detect the issue in cpufetch. I also created a simple example and it does not work either:

```
[drnoob@mininoob cpufetch]$ gcc -v 2>&1 | grep 'gcc ver'
gcc version 10.2.0 (GCC)
[drnoob@mininoob cpufetch]$ clang -v 2>&1 | grep ver
clang version 11.0.1
[drnoob@mininoob cpufetch]$ cat undefined.c 
#include <stdio.h>

int main() {
  printf("%d\n", (int)1 << 31);
}
[drnoob@mininoob cpufetch]$ gcc -fsanitize=undefined undefined.c 
[drnoob@mininoob cpufetch]$
[drnoob@mininoob cpufetch]$ clang -fsanitize=undefined undefined.c 
[drnoob@mininoob cpufetch]$
```

**Comment by stephan-cr** [comment]
It detects these issues at runtime, see https://godbolt.org/z/Mq9YavK8z.

**Comment by Dr-Noob** [comment]
That worked. I didn't expect it to be a runtime detection. I will include for sure the `-fsanitize=undefined` option in a latter commit (I want to fix other things first), I liked it.

Thank you very much for your ideas and your help. Closing the issue.
