### ISSUE TITLE
Suggestion: Add repology badge

### ISSUE THREAD

**Issue by dreua** [Dr-Noob/cpufetch#82]
I like to have a quick overview of available packages, see PDF Arranger as an example: https://github.com/pdfarranger/pdfarranger#linux-packages

[![Packaging status](https://repology.org/badge/vertical-allrepos/cpufetch.svg)](https://repology.org/project/cpufetch/versions)

[cpufetch packaging badges - Repology](https://repology.org/project/cpufetch/badges)

**Comment by Dr-Noob** [comment]
Thanks for your suggestion

I like your idea. I have just uploaded a new commit with your suggestion. Maybe in the future I will have to remove the badge in case it gets too large (but I will keep the small badge at the beginning of the README).

Thanks!

**Comment by dreua** [comment]
Let me know if it gets too large, then I'll look up the multi column option. Thanks for cpufetch!
