### ISSUE TITLE
Auto closes

### ISSUE THREAD

**Issue by MajorGeek** [Dr-Noob/cpufetch#83]
On my Desktop and VMware, the app closes before you can see the details. Tried running as admin with the same results.

**Comment by Dr-Noob** [comment]
Hi, thanks for reporting the issue.

I need additional information about the issue. Please see the [contribution guidelines](https://github.com/Dr-Noob/cpufetch/blob/master/CONTRIBUTING.md#creating-an-issue) for details.

Thanks!

**Comment by Dr-Noob** [comment]
Closing the issue due to lack of activity. Feel free to reopen it if you can provide the required information.

**Comment by MajorGeek** [comment]
No problem. I was reporting it and don't have the time to "read guidelines" to diagnose the problem for you.
