### ISSUE TITLE
[ARM] Raspbian-Raspberry pi Zero 

### ISSUE THREAD

**Issue by Ravenneo** [Dr-Noob/cpufetch#84]
OS: Raspbian GNU/Linux 10 (buster) armv6l 
Host: Raspberry Pi Zero W Rev 1.1 
Kernel: 5.10.17+ 
Shell: bash 5.0.3 
Terminal: /dev/pts/0 
CPU: BCM2835 (1) @ 1.000GHz 
Memory: 34MiB / 430MiB 

./cpufetch --debug
Segmentation fault

**Comment by Dr-Noob** [comment]
Damn...I already fixed that bug, but I forgot to add the fix to master branch.

Thanks for the report. The fix is on master branch now, give it a try and let me know if the problem still happens.

Closing
