### ISSUE TITLE
Make it into a deb package

### ISSUE THREAD

**Issue by hmsjy2017** [Dr-Noob/cpufetch#87]
Compared with binary files, deb packages are easier to install. I hope the deb package can support armhf and arm64.

**Comment by coldtobi** [comment]
Someone is already working on that: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=986783

**Comment by Dr-Noob** [comment]
Sure thing! We are working on it: https://github.com/Dr-Noob/cpufetch/pull/79

**Comment by Dr-Noob** [comment]
Closing. If you wish to continue the conversation, please use this thread: https://github.com/Dr-Noob/cpufetch/pull/79
