### ISSUE TITLE
cpufetch incorrectly reports BCM2835 on Raspberry Pi boards

### ISSUE THREAD

**Issue by hotaru2k3** [Dr-Noob/cpufetch#91]
apparently the correct way to detect which CPU a Raspberry Pi has is to check the revision code:

https://www.raspberrypi.org/documentation/hardware/raspberrypi/revision-codes/README.md

>Note: As of the 4.9 kernel, all Pis report `BCM2835`, even those with BCM2836, BCM2837 and BCM2711 processors. You should not use this string to detect the processor. Decode the revision code using the information below, or `cat /sys/firmware/devicetree/base/model`

>With the launch of the Raspberry Pi 2, new-style revision codes were introduced. Rather than being sequential, each bit of the hex code represents a piece of information about the revision:

>`NOQuuuWuFMMMCCCCPPPPTTTTTTTTRRRR`

>
>PPPP | Processor | 0: BCM2835
>-- | -- | --
>&nbsp; | &nbsp; | 1: BCM2836
>&nbsp; | &nbsp; | 2: BCM2837
>&nbsp; | &nbsp; | 3: BCM2711
>
>

**Comment by Dr-Noob** [comment]
Thank you very much for reporting this issue.

I have checked my RPi and you are actually right; `cpufetch` outputs the wrong SoC in my RPi 2B (it says BCM2835, but should report BCM2836). I have also checked manually the "Revision" and looking at the table, I get the expected BCM2836. This is something that I noticed some time ago (the fact that the SoC was wrong) but had no idea why/how to fix it.

I will push a fix whenever I get some free time. If you own any RPi, I would also appreciate it if you could try the new patch when it's ready.

**Comment by Dr-Noob** [comment]
I've just pushed a fix in a new branch called `rpi`. I have checked it in different RPis and now it correctly detects the CPU. 

If you have any RPi I would appreciate if you could give it a try too.

Thanks!

**Comment by hotaru2k3** [comment]
with that fix it now correctly detects the CPU on my Pi 4.

**Comment by Dr-Noob** [comment]
Nice!

Thanks a lot for the report and for testing the fix in a RPi 4.

Closing the issue and merging the fix to master branch.
