### ISSUE TITLE
[ERROR]: Unknown microarchitecture detected: M=0x00000007 EM=0x0000000A F=0x00000006 EF=0x00000000 S=0x00000001

### ISSUE THREAD

**Issue by BeckyDTP** [Dr-Noob/cpufetch#92]
```
cpufetch v0.94 (x86_64 build)
11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz
- Max standart level: 0x0000001B
- Max extended level: 0x80000008
```

**Comment by Dr-Noob** [comment]
Hi, thanks for the report.

You are using an old cpufetch version (v0.94), current version is v0.98. The support for rocket lake processors was added some time ago, so it should work in the latest version. To get the latest version, you need to [build cpufetch from source](https://github.com/Dr-Noob/cpufetch#22-building-from-source-linuxwindowsmacos). If you don't know how to do so, you will have until I release a new compiled version of cpufetch.

**Comment by BeckyDTP** [comment]
OK.
