### ISSUE TITLE
Does not compile on FreeBSD with LLVM (src/x86/apic.c:80:5: error: unknown type name 'cpu_set_t'; did you mean 'cpusetid_t'?)

### ISSUE THREAD

**Issue by MikeJakubik** [Dr-Noob/cpufetch#93]
[root@fbsd-head /tmp/cpufetch]# gmake
cc -Wall -Wextra -pedantic -fstack-protector-all -pedantic -std=c99 -DARCH_X86 -O3 -Wfloat-equal -Wshadow -Wpointer-arith src/common/main.c src/common/cpu.c src/common/udev.c src/common/printer.c src/common/args.c src/common/global.c src/x86/cpuid.c src/x86/apic.c src/x86/cpuid_asm.c src/x86/uarch.c -o cpufetch
src/x86/apic.c:80:5: error: unknown type name 'cpu_set_t'; did you mean 'cpusetid_t'?
    cpu_set_t currentCPU;
    ^~~~~~~~~
    cpusetid_t
/usr/include/sys/types.h:86:22: note: 'cpusetid_t' declared here
typedef __cpusetid_t    cpusetid_t;
                        ^
src/x86/apic.c:81:5: warning: implicit declaration of function 'CPU_ZERO' is invalid in C99 [-Wimplicit-function-declaration]
    CPU_ZERO(&currentCPU);
    ^
src/x86/apic.c:82:5: warning: implicit declaration of function 'CPU_SET' is invalid in C99 [-Wimplicit-function-declaration]
    CPU_SET(cpu_id, &currentCPU);
    ^
src/x86/apic.c:83:9: warning: implicit declaration of function 'sched_setaffinity' is invalid in C99 [-Wimplicit-function-declaration]
    if (sched_setaffinity (0, sizeof(currentCPU), &currentCPU) == -1) {
        ^
3 warnings and 1 error generated.
gmake: *** [Makefile:29: cpufetch] Error 1

[root@fbsd-head /tmp/cpufetch]# uname -a
FreeBSD fbsd-head 14.0-CURRENT FreeBSD 14.0-CURRENT #0 main-d7bfb412a: Sun Jun  6 10:08:22 EDT 2021     root@fbsd-head:/usr/obj/usr/src/amd64.amd64/sys/HYPERV  amd64

[root@fbsd-head /tmp/cpufetch]# cc -v
FreeBSD clang version 11.0.1 (git@github.com:llvm/llvm-project.git llvmorg-11.0.1-0-g43ff75f2c3fe)
Target: x86_64-unknown-freebsd14.0
Thread model: posix
InstalledDir: /usr/bin

**Comment by Dr-Noob** [comment]
Thank you for your report. You're the first who has tried to run `cpufetch` in FreeBSD. 

It is no surprise that there are some things that do not work exactly the same as Linux...I will have a look and will upload a fix to compile `cpufetch` in FreeBSD.

**Comment by MikeJakubik** [comment]
Thanks, let me know if you want me to test any patches.

**Comment by Dr-Noob** [comment]
Hi, I've just pushed a patch that should let you at least compile the program. The patch is in a new branch called `freebsd`. Please checkout to the branch (`git checkout freebsd`) and git it a try. 

Thanks!

**Comment by MikeJakubik** [comment]
Seems to work great! You even fixed the Makefile to include amd64 arch,ty.

![Capture](https://user-images.githubusercontent.com/73555475/122658060-e24bf500-d136-11eb-97cb-1541d36bb2e3.PNG)

**Comment by Dr-Noob** [comment]
That's nice! 

Not related to FreeBSD but some of the data seem to be wrong. I guess that the number of cores is wrong due to the fact that its a VM and you set the number of cores to 8. The cache seems wrong too. Could you test this outside of the VM? `cpufetch --verbose` and `cpufetch --debug` may help to find the issue.

Thanks

**Comment by MikeJakubik** [comment]
Yes, though the VM is set to 10 cores, not 8.

[root@fbsd-head /tmp/cpufetch-freebsd]# ./cpufetch --verbose
[WARNING]: Can't read frequency information from cpuid (needed level is 0x00000016, max is 0x0000000D). Using udev
[WARNING]: Could not open '/sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq' (HV is present)

[root@fbsd-head /tmp/cpufetch-freebsd]# ./cpufetch --debug
cpufetch v0.98 (Unknown OS x86_64 build)
AMD Ryzen 9 5950X 16-Core Processor
- Hypervisor: Microsoft Hyper-V
- Max standard level: 0x0000000D
- Max extended level: 0x8000001E
- AMD topology extensions: 1
- CPUID dump: 0x00A20F10

Here is the CPU info from OS on boot.

CPU: AMD Ryzen 9 5950X 16-Core Processor             (3399.99-MHz K8-class CPU)
  Origin="AuthenticAMD"  Id=0xa20f10  Family=0x19  Model=0x21  Stepping=0
  Features=0x1783fbff<FPU,VME,DE,PSE,TSC,MSR,PAE,MCE,CX8,APIC,SEP,MTRR,PGE,MCA,CMOV,PAT,PSE36,MMX,FXSR,SSE,SSE2,HTT>
  Features2=0xfed83203<SSE3,PCLMULQDQ,SSSE3,FMA,CX16,SSE4.1,SSE4.2,MOVBE,POPCNT,AESNI,XSAVE,OSXSAVE,AVX,F16C,RDRAND,HV>
  AMD Features=0x2e500800<SYSCALL,NX,MMX+,FFXSR,Page1GB,RDTSCP,LM>
  AMD Features2=0x4003f3<LAHF,CMP,CR8,ABM,SSE4A,MAS,Prefetch,OSVW,Topology>
  Structured Extended Features=0x219c03a9<FSGSBASE,BMI1,AVX2,SMEP,BMI2,ERMS,RDSEED,ADX,SMAP,CLFLUSHOPT,CLWB,SHA>
  Structured Extended Features2=0x400600<VAES,VPCLMULQDQ,RDPID>
  Structured Extended Features3=0x10<FSRM>
  XSAVE Features=0xf<XSAVEOPT,XSAVEC,XINUSE,XSAVES>
  AMD Extended Feature Extensions ID EBX=0xd004<XSaveErPtr,IBPB,IBRS,STIBP>
FreeBSD/SMP: Multiprocessor System Detected: 10 CPUs
FreeBSD/SMP: 1 package(s) x 5 core(s) x 2 hardware threads

I also ran it on some other bare metal, don't have FreeBSD on this machine at this time, but i can get you some data soon.

![Capture](https://user-images.githubusercontent.com/73555475/122768554-b5502d00-d271-11eb-992a-b64e99d04ae8.PNG)

**Comment by Dr-Noob** [comment]
Nice, so it looks like the FreeBSD issue is solved. If you are interested in investigating the issue regarding the number of cores, feel free to open another issue.

Thanks!
