### ISSUE TITLE
Unknown microarchitecture detected

### ISSUE THREAD

**Issue by sm-moshi** [Dr-Noob/cpufetch#97]
Hey ho,

on my new work notebook cpufetch told me I should open an issue. So here it is:

❯ cpufetch --debug
[ERROR]: Unknown microarchitecture detected: M=0x00000008 EM=0x00000006 F=0x0000000F EF=0x00000008 S=0x00000001
Please, create a new issue with this error message and the output of 'cpufetch --debug' in https://github.com/Dr-Noob/cpufetch/issues
cpufetch v0.98 (Linux x86_64 build)
AMD Ryzen 7 5700U with Radeon Graphics 
- Max standard level: 0x00000010
- Max extended level: 0x80000020
- AMD topology extensions: 1
- CPUID dump: 0x00860F81

I hope it helps someone somehow. :)

Greets
![Screenshot_20210726_162019](https://user-images.githubusercontent.com/12695314/127004697-0695bce4-1fb4-4797-b872-1c70598011ba.png)

**Comment by Dr-Noob** [comment]
Hi, thanks for the report! 

Yeah, it helps a lot. I didn't know that I had a CPU family missing in the microarchitecture table. I have just added it, please download and build the code again to check if it works now. If so, feel free to close the issue.

**Comment by sm-moshi** [comment]
It did work! Thank you. :)
